#!/bin/bash
###############################################################################
# Linux Health Check Script - Banking Production Environment
# Compatible: Oracle Linux 8, 9, 10 (RHEL-compatible) / vSphere VMs
# Purpose:    Comprehensive daily health + security + compliance check
# Output:     /root/Linux_health/<hostname>_health_YYYYMMDD.txt & .html
# Scheduling: Systemd Timer (cron-free, banking compliance)
# Author:     Infrastructure Automation Team
# Version:    3.0
###############################################################################

set -o pipefail

#=============================================================================
# CONFIGURABLE THRESHOLDS (per-metric, editable per environment)
#=============================================================================
THRESH_CPU=85              # CPU utilization %
THRESH_MEMORY=85           # Memory utilization %
THRESH_SWAP=70             # Swap utilization % (lower = early warning)
THRESH_DISK_UTIL=85        # Disk I/O utilization %
THRESH_DISK_AWAIT=50       # Disk await (ms)
THRESH_FS=85               # Filesystem usage %
THRESH_NFS_RETRANS=5       # NFS retransmission %
THRESH_LOAD_FACTOR=2       # Load avg = factor x CPU_count
THRESH_FAILED_LOGIN=5      # Failed logins per source IP (brute force)
THRESH_CERT_WARN_DAYS=30   # Certificate expiry warning (days)
THRESH_CERT_CRIT_DAYS=7    # Certificate expiry critical (days)
THRESH_ZOMBIE=10           # Zombie process count
THRESH_LOG_SIZE_MB=1024    # Log file size warning (MB)
THRESH_PATCH_DAYS=30       # Days since last patching

#=============================================================================
# ALERTING CONFIGURATION
#=============================================================================
ENABLE_EMAIL_ALERT="yes"
ENABLE_SALT_EVENT="yes"
EMAIL_RECIPIENTS="unix-team@bank.com,infra-alerts@bank.com"
EMAIL_SUBJECT_PREFIX="[LINUX-HEALTH]"
SALT_EVENT_TAG="infra/health/alert"

#=============================================================================
# BANK BRANDING (for HTML report)
#=============================================================================
BANK_NAME="Your Bank Name"
BANK_LOGO_PATH=""
REPORT_FOOTER="Generated by Infrastructure Automation | Confidential & Internal Use Only"

#=============================================================================
# SECURITY BASELINES (CIS Benchmark reference values)
#=============================================================================
CIS_PASS_MAX_DAYS=90
CIS_PASS_MIN_DAYS=7
CIS_PASS_MIN_LEN=14
CIS_PASS_WARN_AGE=7
CIS_UMASK="027"

# Kernel parameters expected by CIS
declare -A CIS_SYSCTL=(
    ["net.ipv4.ip_forward"]="0"
    ["net.ipv4.conf.all.accept_redirects"]="0"
    ["net.ipv4.conf.default.accept_redirects"]="0"
    ["net.ipv4.conf.all.send_redirects"]="0"
    ["net.ipv4.conf.default.send_redirects"]="0"
    ["net.ipv4.conf.all.accept_source_route"]="0"
    ["net.ipv4.conf.all.log_martians"]="1"
    ["net.ipv4.icmp_echo_ignore_broadcasts"]="1"
    ["net.ipv4.icmp_ignore_bogus_error_responses"]="1"
    ["net.ipv4.conf.all.rp_filter"]="1"
    ["net.ipv4.tcp_syncookies"]="1"
    ["net.ipv6.conf.all.accept_redirects"]="0"
    ["net.ipv6.conf.default.accept_redirects"]="0"
    ["kernel.randomize_va_space"]="2"
    ["fs.suid_dumpable"]="0"
    ["kernel.exec-shield"]="1"
)

# Disabled kernel modules (CIS)
CIS_DISABLED_MODULES="cramfs freevxfs jffs2 hfs hfsplus squashfs udf usb-storage"

#=============================================================================
# CERTIFICATE SCAN PATHS
#=============================================================================
CERT_SCAN_PATHS="/etc/pki/tls/certs /etc/ssl/certs /etc/pki/ca-trust /opt/certs /app/certs"

#=============================================================================
# BACKUP AGENT PROCESSES (customize per environment)
#=============================================================================
BACKUP_AGENTS="bpcd|bpbkar|vnetd|nbdisco|cvd|clBackup|veeamAgent|tsm|dsmc"

#=============================================================================
# ORACLE DATABASE PROCESSES
#=============================================================================
ORACLE_PROCS="ora_pmon|ora_smon|ora_dbw|ora_lgwr|ora_ckpt|ora_arc|ora_mmon|tnslsnr|ocssd|crsd|evmd"

#=============================================================================
# INTERNAL VARIABLES - DO NOT EDIT BELOW
#=============================================================================
HOSTNAME_S=$(hostname -s)
DATE_STAMP=$(date +%Y%m%d)
TIME_STAMP=$(date '+%Y-%m-%d %H:%M:%S')
REPORT_DIR="/root/Linux_health"
TXT_FILE="${REPORT_DIR}/${HOSTNAME_S}_health_${DATE_STAMP}.txt"
HTML_FILE="${REPORT_DIR}/${HOSTNAME_S}_health_${DATE_STAMP}.html"
ALERT_LOG="${REPORT_DIR}/.alert_findings_${DATE_STAMP}.tmp"
CPU_COUNT=$(nproc 2>/dev/null || grep -c ^processor /proc/cpuinfo)
OS_VERSION=$(cat /etc/oracle-release 2>/dev/null || cat /etc/redhat-release 2>/dev/null || echo "Unknown")
KERNEL=$(uname -r)
UPTIME_STR=$(uptime -p 2>/dev/null || uptime)
LAST_REBOOT=$(who -b 2>/dev/null | awk '{print $3,$4}')
SAR_DIR="/var/log/sa"
YESTERDAY=$(date -d "yesterday" +%d)
TODAY=$(date +%d)

mkdir -p "${REPORT_DIR}"
> "${ALERT_LOG}"

#=============================================================================
# UTILITY FUNCTIONS
#=============================================================================
log_alert() {
    echo "${1}|${2}|${3}|${4}" >> "${ALERT_LOG}"
}

check_command() {
    command -v "$1" &>/dev/null
}

pct_bar() {
    local pct=${1%%.*}
    [[ -z "$pct" || "$pct" == "N/A" ]] && pct=0
    local filled=$((pct / 5))
    local empty=$((20 - filled))
    printf '[%s%s] %3d%%' "$(printf '#%.0s' $(seq 1 $filled 2>/dev/null))" \
           "$(printf '.%.0s' $(seq 1 $empty 2>/dev/null))" "$pct"
}

get_sar_file() {
    local day="$1"
    local sar_bin="${SAR_DIR}/sa${day}"
    [[ -f "$sar_bin" ]] && echo "$sar_bin" || echo ""
}

divider() {
    echo "--------------------------------------------------------------------------------"
}

section_header() {
    echo ""
    echo "[$1] $2"
    divider
}

#=============================================================================
# SECTION 0: PRE-FLIGHT DEPENDENCY CHECK (warn only, no auto-install)
#=============================================================================
check_dependencies() {
    echo "================================================================================"
    echo "  PRE-FLIGHT: DEPENDENCY CHECK"
    echo "================================================================================"
    echo ""

    local missing=0
    declare -A DEPS=(
        ["sysstat"]="sar iostat mpstat (historical analysis)"
        ["bc"]="threshold calculations"
        ["nfs-utils"]="nfsstat nfsiostat (NFS health)"
        ["lsof"]="open port / file handle analysis"
        ["net-tools"]="netstat (legacy network checks)"
        ["iproute"]="ss (socket statistics)"
        ["audit"]="auditd (audit daemon health)"
        ["aide"]="file integrity monitoring"
        ["openssl"]="certificate expiry checks"
    )

    printf "  %-20s %-10s %s\n" "PACKAGE" "STATUS" "PURPOSE"
    divider

    for pkg in sysstat bc nfs-utils lsof net-tools iproute audit aide openssl; do
        if rpm -q "$pkg" &>/dev/null; then
            printf "  %-20s %-10s %s\n" "$pkg" "[OK]" "${DEPS[$pkg]}"
        else
            printf "  %-20s %-10s %s\n" "$pkg" "[MISSING]" "${DEPS[$pkg]}"
            missing=$((missing + 1))
            log_alert "WARNING" "DEPENDENCY" "Package '${pkg}' not installed - ${DEPS[$pkg]}" \
                "Install: yum install -y ${pkg} (or) dnf install -y ${pkg}"
        fi
    done

    # Check individual commands even if package names differ
    echo ""
    echo "  Command availability:"
    for cmd in sar iostat mpstat bc ss lsof auditctl aide openssl mail salt-call; do
        if check_command "$cmd"; then
            printf "  %-20s [AVAILABLE]\n" "$cmd"
        else
            printf "  %-20s [NOT FOUND]\n" "$cmd"
        fi
    done

    if (( missing > 0 )); then
        echo ""
        echo "  *** WARNING: ${missing} package(s) missing. Some checks will be skipped. ***"
        echo "  *** Install missing packages to enable full health check coverage.       ***"
    fi
    echo ""
}

#=============================================================================
# SECTION 1: SYSTEM IDENTITY & UPTIME
#=============================================================================
collect_system_info() {
    echo "================================================================================"
    echo "  LINUX HEALTH CHECK REPORT - ${BANK_NAME}"
    echo "  Host: ${HOSTNAME_S} | Date: ${TIME_STAMP}"
    echo "  Version: 3.0 | Includes: Performance + Security + VAPT + CIS Compliance"
    echo "================================================================================"

    section_header "1" "SYSTEM IDENTITY"
    printf "  Hostname       : %s\n" "$(hostname -f 2>/dev/null || hostname)"
    printf "  OS Release     : %s\n" "${OS_VERSION}"
    printf "  Kernel         : %s\n" "${KERNEL}"
    printf "  Architecture   : %s\n" "$(uname -m)"
    printf "  CPU Count      : %s\n" "${CPU_COUNT}"
    printf "  Uptime         : %s\n" "${UPTIME_STR}"
    printf "  Last Reboot    : %s\n" "${LAST_REBOOT}"
    printf "  SELinux Status : %s\n" "$(getenforce 2>/dev/null || echo 'N/A')"
    printf "  vSphere VM     : %s\n" "$(dmidecode -s system-product-name 2>/dev/null | head -1 || echo 'N/A')"
    printf "  Run Date       : %s\n" "${TIME_STAMP}"
    echo ""
}

#=============================================================================
# SECTION 2: CPU STATISTICS
#=============================================================================
collect_cpu_stats() {
    section_header "2" "CPU STATISTICS"

    if check_command mpstat; then
        echo "  >> Current CPU Utilization (mpstat 1 3 average):"
        local mpstat_out
        mpstat_out=$(mpstat 1 3 2>/dev/null | tail -1)
        local idle=$(echo "$mpstat_out" | awk '{print $NF}')
        local usage
        usage=$(echo "100 - ${idle}" | bc 2>/dev/null || echo "N/A")
        echo "     Overall CPU Usage : ${usage}%"
        if [[ "$usage" != "N/A" ]] && (( $(echo "$usage > $THRESH_CPU" | bc -l 2>/dev/null || echo 0) )); then
            log_alert "CRITICAL" "CPU" "Current CPU usage at ${usage}% (threshold: ${THRESH_CPU}%)" \
                "Investigate top CPU consumers. Notify Application/Oracle team if DB processes dominate."
        fi
        echo ""
        mpstat -P ALL 1 1 2>/dev/null | head -20
    else
        echo "  [SKIPPED] mpstat not available (install sysstat)"
        top -bn1 | head -5
    fi

    echo ""
    echo "  >> Load Average:"
    local load_1 load_5 load_15
    read load_1 load_5 load_15 _ < /proc/loadavg
    local load_thresh=$((CPU_COUNT * THRESH_LOAD_FACTOR))
    printf "     1-min: %-8s  5-min: %-8s  15-min: %-8s  (threshold: %d)\n" \
           "$load_1" "$load_5" "$load_15" "$load_thresh"
    if (( $(echo "$load_1 > $load_thresh" | bc -l 2>/dev/null || echo 0) )); then
        log_alert "WARNING" "CPU-LOAD" "Load average ${load_1} exceeds threshold ${load_thresh}" \
            "High load detected. Check for runaway processes."
    fi

    echo ""
    echo "  >> Top 5 CPU Consuming Processes:"
    printf "     %-8s %-6s %-6s %-10s %s\n" "PID" "%CPU" "%MEM" "USER" "COMMAND"
    echo "     -------------------------------------------------------"
    ps aux --sort=-%cpu | head -6 | tail -5 | while read user pid cpu mem vsz rss tty stat start time cmd; do
        printf "     %-8s %-6s %-6s %-10s %s\n" "$pid" "$cpu" "$mem" "$user" "${cmd:0:50}"
    done

    echo ""
    echo "  >> Oracle Process CPU Check:"
    local ora_cpu
    ora_cpu=$(ps aux | grep -E "${ORACLE_PROCS}" | grep -v grep)
    if [[ -n "$ora_cpu" ]]; then
        echo "$ora_cpu" | sort -k3 -rn | head -5 | while read user pid cpu mem vsz rss tty stat start time cmd; do
            printf "     %-8s %-6s %-6s %-10s %s\n" "$pid" "$cpu" "$mem" "$user" "${cmd:0:50}"
            if (( $(echo "$cpu > $THRESH_CPU" | bc -l 2>/dev/null || echo 0) )); then
                log_alert "CRITICAL" "ORACLE-CPU" "Oracle process ${cmd:0:30} (PID:${pid}) at ${cpu}% CPU" \
                    "Notify Oracle DBA team. Check for long-running queries or rman jobs."
            fi
        done
    else
        echo "     No Oracle processes detected."
    fi
    echo ""
}

#=============================================================================
# SECTION 3: MEMORY STATISTICS
#=============================================================================
collect_memory_stats() {
    section_header "3" "MEMORY STATISTICS"

    local mem_total mem_used mem_free mem_available mem_buffers mem_cached mem_pct
    mem_total=$(grep MemTotal /proc/meminfo | awk '{print $2}')
    mem_free=$(grep MemFree /proc/meminfo | awk '{print $2}')
    mem_available=$(grep MemAvailable /proc/meminfo | awk '{print $2}')
    mem_buffers=$(grep Buffers /proc/meminfo | awk '{print $2}')
    mem_cached=$(grep "^Cached:" /proc/meminfo | awk '{print $2}')
    mem_used=$((mem_total - mem_free - mem_buffers - mem_cached))
    mem_pct=$((mem_used * 100 / mem_total))

    local total_gb=$(echo "scale=2; $mem_total/1048576" | bc 2>/dev/null || echo "N/A")
    local used_gb=$(echo "scale=2; $mem_used/1048576" | bc 2>/dev/null || echo "N/A")
    local free_gb=$(echo "scale=2; $mem_free/1048576" | bc 2>/dev/null || echo "N/A")
    local avail_gb=$(echo "scale=2; $mem_available/1048576" | bc 2>/dev/null || echo "N/A")
    local buf_gb=$(echo "scale=2; $mem_buffers/1048576" | bc 2>/dev/null || echo "N/A")
    local cache_gb=$(echo "scale=2; $mem_cached/1048576" | bc 2>/dev/null || echo "N/A")

    echo "  >> Physical Memory:"
    printf "     Total: %-10s  Used: %-10s  Free: %-10s\n" "${total_gb} GB" "${used_gb} GB" "${free_gb} GB"
    printf "     Available: %-10s  Buffers: %-10s  Cached: %-10s\n" "${avail_gb} GB" "${buf_gb} GB" "${cache_gb} GB"
    printf "     Utilization: %s\n" "$(pct_bar $mem_pct)"

    if (( mem_pct > THRESH_MEMORY )); then
        log_alert "CRITICAL" "MEMORY" "Memory utilization at ${mem_pct}% (threshold: ${THRESH_MEMORY}%)" \
            "Investigate high memory consumers. Notify Application team for memory leak / Oracle DBA for SGA/PGA tuning."
    fi

    echo ""
    echo "  >> Huge Pages (Oracle relevant):"
    grep -i huge /proc/meminfo 2>/dev/null | while read line; do echo "     $line"; done

    echo ""
    echo "  >> Top 5 Memory Consumers:"
    printf "     %-8s %-6s %-12s %-10s %s\n" "PID" "%MEM" "RSS(MB)" "USER" "COMMAND"
    echo "     -------------------------------------------------------"
    ps aux --sort=-%mem | head -6 | tail -5 | while read user pid cpu mem vsz rss tty stat start time cmd; do
        local rss_mb=$((rss / 1024))
        printf "     %-8s %-6s %-12s %-10s %s\n" "$pid" "$mem" "$rss_mb" "$user" "${cmd:0:50}"
    done
    echo ""
}

#=============================================================================
# SECTION 4: SWAP UTILIZATION
#=============================================================================
collect_swap_stats() {
    section_header "4" "SWAP UTILIZATION"

    local swap_total swap_used swap_free swap_pct
    swap_total=$(grep SwapTotal /proc/meminfo | awk '{print $2}')
    swap_used=$((swap_total - $(grep SwapFree /proc/meminfo | awk '{print $2}')))
    swap_free=$(grep SwapFree /proc/meminfo | awk '{print $2}')

    if (( swap_total > 0 )); then
        swap_pct=$((swap_used * 100 / swap_total))
    else
        swap_pct=0
    fi

    local stotal_gb=$(echo "scale=2; $swap_total/1048576" | bc 2>/dev/null || echo "N/A")
    local sused_gb=$(echo "scale=2; $swap_used/1048576" | bc 2>/dev/null || echo "N/A")
    local sfree_gb=$(echo "scale=2; $swap_free/1048576" | bc 2>/dev/null || echo "N/A")

    printf "     Total: %-10s  Used: %-10s  Free: %-10s\n" "${stotal_gb} GB" "${sused_gb} GB" "${sfree_gb} GB"
    printf "     Utilization: %s\n" "$(pct_bar $swap_pct)"

    if (( swap_pct > THRESH_SWAP )); then
        log_alert "CRITICAL" "SWAP" "Swap usage at ${swap_pct}% (threshold: ${THRESH_SWAP}%)" \
            "High swap = memory pressure. Notify Application/Oracle team."
    fi

    echo ""
    echo "  >> Top 10 Processes Consuming Swap:"
    printf "     %-8s %-12s %-10s %s\n" "PID" "SWAP(MB)" "USER" "COMMAND"
    echo "     -------------------------------------------------------"

    for pid_dir in /proc/[0-9]*; do
        local pid=$(basename "$pid_dir")
        local swap_kb=0
        if [[ -f "${pid_dir}/smaps_rollup" ]]; then
            swap_kb=$(awk '/^Swap:/{sum+=$2}END{print sum+0}' "${pid_dir}/smaps_rollup" 2>/dev/null)
        elif [[ -f "${pid_dir}/smaps" ]]; then
            swap_kb=$(awk '/^Swap:/{sum+=$2}END{print sum+0}' "${pid_dir}/smaps" 2>/dev/null)
        fi
        if [[ -n "$swap_kb" ]] && (( swap_kb > 1024 )); then
            local cmd_name=$(cat "${pid_dir}/comm" 2>/dev/null || echo "unknown")
            local proc_user=$(stat -c '%U' "${pid_dir}" 2>/dev/null || echo "unknown")
            echo "${swap_kb} ${pid} ${proc_user} ${cmd_name}"
        fi
    done 2>/dev/null | sort -rn | head -10 | while read swap_kb pid user cmd; do
        local swap_mb=$((swap_kb / 1024))
        printf "     %-8s %-12s %-10s %s\n" "$pid" "$swap_mb" "$user" "${cmd:0:50}"
    done
    echo ""
}

#=============================================================================
# SECTION 5: DISK I/O & LATENCY
#=============================================================================
collect_disk_io() {
    section_header "5" "DISK I/O & LATENCY"

    if check_command iostat; then
        echo "  >> Current I/O Statistics (iostat -xd 1 2):"
        printf "     %-12s %8s %8s %8s %8s %8s %8s %8s\n" \
               "DEVICE" "rrqm/s" "wrqm/s" "r/s" "w/s" "await" "svctm" "%util"
        echo "     ---------------------------------------------------------------------------"

        iostat -xd 1 2 2>/dev/null | awk '
        NR>1 && /^[a-z]/ && seen[$1]++ {
            printf "     %-12s %8s %8s %8s %8s %8s %8s %8s\n",
                   $1, $2, $3, $4, $5, $(NF-2), $(NF-1), $NF
        }' | while read line; do
            echo "$line"
            local dev=$(echo "$line" | awk '{print $1}')
            local util=$(echo "$line" | awk '{print $NF}')
            local await=$(echo "$line" | awk '{print $(NF-2)}')
            if (( $(echo "${util} > ${THRESH_DISK_UTIL}" | bc -l 2>/dev/null || echo 0) )); then
                log_alert "CRITICAL" "DISK-IO" "Device ${dev} I/O utilization at ${util}% (threshold: ${THRESH_DISK_UTIL}%)" \
                    "High disk I/O on ${dev}. Notify Application/Oracle team if DB datafiles reside here."
            fi
            if (( $(echo "${await} > ${THRESH_DISK_AWAIT}" | bc -l 2>/dev/null || echo 0) )); then
                log_alert "WARNING" "DISK-LATENCY" "Device ${dev} await at ${await}ms (threshold: ${THRESH_DISK_AWAIT}ms)" \
                    "High disk latency. Possible storage bottleneck. Engage Storage/VMware team."
            fi
        done
    else
        echo "  [SKIPPED] iostat not available (install sysstat)"
    fi
    echo ""
}

#=============================================================================
# SECTION 6: FILESYSTEM UTILIZATION
#=============================================================================
collect_filesystem_stats() {
    section_header "6" "FILESYSTEM UTILIZATION"

    echo "  >> Local & SAN Filesystems:"
    printf "     %-35s %8s %8s %8s %6s %s\n" "FILESYSTEM" "SIZE" "USED" "AVAIL" "USE%" "MOUNT"
    echo "     ---------------------------------------------------------------------------------"

    df -hP -x tmpfs -x devtmpfs -x nfs -x nfs4 -x fuse.s3fs 2>/dev/null | tail -n +2 | sort -k5 -rn | while read fs size used avail pct mount; do
        local pct_num=${pct%%%}
        local flag=""
        if (( pct_num >= THRESH_FS )); then
            flag=" *** ALERT ***"
            log_alert "CRITICAL" "FILESYSTEM" "Filesystem ${mount} (${fs}) at ${pct} (threshold: ${THRESH_FS}%)" \
                "Filesystem nearing capacity. Identify large files/logs. Extend via LVM or cleanup."
        fi
        printf "     %-35s %8s %8s %8s %6s %s%s\n" "$fs" "$size" "$used" "$avail" "$pct" "$mount" "$flag"
    done

    echo ""
    echo "  >> Inode Utilization (>50%):"
    df -iP -x tmpfs -x devtmpfs -x nfs -x nfs4 2>/dev/null | tail -n +2 | while read fs total used free pct mount; do
        local pct_num=${pct%%%}
        if (( pct_num > 50 )); then
            printf "     %-35s %6s %s\n" "$fs" "$pct" "$mount"
            if (( pct_num >= THRESH_FS )); then
                log_alert "WARNING" "INODE" "Inode usage on ${mount} at ${pct}" \
                    "High inode usage - excessive small files. Identify and cleanup."
            fi
        fi
    done
    echo ""
}

#=============================================================================
# SECTION 7: NFS HEALTH
#=============================================================================
collect_nfs_health() {
    section_header "7" "NFS HEALTH"

    local nfs_mounts
    nfs_mounts=$(mount -t nfs,nfs4 2>/dev/null)
    if [[ -z "$nfs_mounts" ]]; then
        echo "     No NFS mounts detected."
        echo ""
        return
    fi

    echo "  >> NFS Mount Points:"
    printf "     %-40s %-20s %-8s %s\n" "SOURCE" "MOUNT" "TYPE" "OPTIONS"
    echo "     ---------------------------------------------------------------------------------"
    mount -t nfs,nfs4 2>/dev/null | while read src on mnt type fstype opts; do
        printf "     %-40s %-20s %-8s %s\n" "$src" "$mnt" "$fstype" "${opts:0:40}"
    done

    echo ""
    echo "  >> NFS Mount Responsiveness (5s timeout):"
    mount -t nfs,nfs4 2>/dev/null | awk '{print $3}' | while read mnt; do
        local start_ts=$(date +%s%N)
        if timeout 5 stat "$mnt" &>/dev/null; then
            local end_ts=$(date +%s%N)
            local latency_ms=$(( (end_ts - start_ts) / 1000000 ))
            printf "     %-30s : RESPONSIVE (%dms)\n" "$mnt" "$latency_ms"
            if (( latency_ms > 3000 )); then
                log_alert "WARNING" "NFS-SLOW" "NFS mount ${mnt} slow (${latency_ms}ms)" \
                    "NFS latency issue. Engage Network/Storage team."
            fi
        else
            printf "     %-30s : *** HUNG/TIMEOUT ***\n" "$mnt"
            log_alert "CRITICAL" "NFS-HUNG" "NFS mount ${mnt} HUNG or not responding" \
                "IMMEDIATE: NFS mount hung. Check NFS server, network. May need umount -f."
        fi
    done

    echo ""
    echo "  >> NFS Filesystem Utilization:"
    df -hP -t nfs -t nfs4 2>/dev/null | tail -n +2 | while read fs size used avail pct mount; do
        local pct_num=${pct%%%}
        local flag=""
        if (( pct_num >= THRESH_FS )); then
            flag=" *** ALERT ***"
            log_alert "WARNING" "NFS-SPACE" "NFS mount ${mount} at ${pct}" \
                "NFS share nearing capacity. Coordinate with NFS server admin."
        fi
        printf "     %-35s %8s %8s %8s %6s %s%s\n" "$fs" "$size" "$used" "$avail" "$pct" "$mount" "$flag"
    done

    if check_command nfsstat; then
        echo ""
        echo "  >> NFS RPC Statistics:"
        nfsstat -c 2>/dev/null | head -15 | sed 's/^/     /'
    fi

    echo ""
    echo "  >> Stale NFS Handle Check:"
    local stale_count=$(dmesg 2>/dev/null | grep -ci "stale.*nfs\|nfs.*stale" || echo 0)
    if (( stale_count > 0 )); then
        echo "     *** ${stale_count} stale NFS handle message(s) in dmesg ***"
        log_alert "WARNING" "NFS-STALE" "${stale_count} stale NFS handle errors" \
            "Stale handles detected. Remount may be required."
    else
        echo "     No stale NFS handles."
    fi
    echo ""
}

#=============================================================================
# SECTION 8: S3FS MOUNT STATISTICS
#=============================================================================
collect_s3fs_stats() {
    section_header "8" "S3FS MOUNT STATISTICS"

    local s3fs_mounts
    s3fs_mounts=$(mount -t fuse.s3fs 2>/dev/null || grep s3fs /proc/mounts 2>/dev/null)
    if [[ -z "$s3fs_mounts" ]]; then
        echo "     No S3FS mounts detected."
        echo ""
        return
    fi

    echo "$s3fs_mounts" | while read src mnt fstype opts rest; do
        printf "     Source: %-30s  Mount: %-20s\n" "$src" "$mnt"
        if timeout 10 stat "$mnt" &>/dev/null; then
            echo "     Status: RESPONSIVE"
            df -hP "$mnt" 2>/dev/null | tail -1 | while read fs size used avail pct mount; do
                printf "     Size: %-8s  Used: %-8s  Available: %-8s  Usage: %s\n" "$size" "$used" "$avail" "$pct"
            done
        else
            echo "     Status: *** NOT RESPONDING ***"
            log_alert "CRITICAL" "S3FS" "S3FS mount ${mnt} not responding" \
                "Check AWS credentials, network, s3fs process. Engage Cloud team."
        fi
        echo ""
    done
}

#=============================================================================
# SECTION 9: SAR HISTORICAL ANALYSIS (LAST 24 HOURS)
#=============================================================================
collect_historical_stats() {
    section_header "9" "HISTORICAL ANALYSIS - LAST 24 HOURS (SAR DATA)"
    echo "================================================================================"

    local sar_yesterday sar_today
    sar_yesterday=$(get_sar_file "$YESTERDAY")
    sar_today=$(get_sar_file "$TODAY")

    if [[ -z "$sar_yesterday" && -z "$sar_today" ]]; then
        echo "  *** SAR data not available. Ensure sysstat is installed and sa1/sa2 are running. ***"
        log_alert "WARNING" "SAR-DATA" "SAR data files not found in ${SAR_DIR}" \
            "Install/enable sysstat: yum install sysstat && systemctl enable --now sysstat"
        echo ""
        return
    fi

    # ---- 9a: CPU Historical ----
    echo ""
    echo "  [9a] CPU Usage History (sar -u)"
    echo "  -----------------------------------------------"
    for sar_file in "$sar_yesterday" "$sar_today"; do
        [[ -z "$sar_file" || ! -f "$sar_file" ]] && continue
        local day_label
        [[ "$sar_file" == *"sa${YESTERDAY}" ]] && day_label="YESTERDAY" || day_label="TODAY"
        echo "  -- ${day_label} --"
        sar -u -f "$sar_file" 2>/dev/null | grep -v "^$\|Linux\|Average\|%idle\|RESTART" | \
        awk -v thresh="$THRESH_CPU" '{
            idle=$NF; cpu=100-idle;
            if(cpu>max) max=cpu
            if(cpu>thresh) { printf "     BREACH: %s - CPU %.1f%%\n", $1, cpu; count++ }
        } END {
            printf "     Peak CPU: %.1f%%\n", max
            if(count>0) printf "     Total breaches: %d intervals\n", count
        }'
        echo ""
    done

    # ---- 9b: Memory Historical ----
    echo "  [9b] Memory Usage History (sar -r)"
    echo "  -----------------------------------------------"
    for sar_file in "$sar_yesterday" "$sar_today"; do
        [[ -z "$sar_file" || ! -f "$sar_file" ]] && continue
        local day_label
        [[ "$sar_file" == *"sa${YESTERDAY}" ]] && day_label="YESTERDAY" || day_label="TODAY"
        echo "  -- ${day_label} --"
        sar -r -f "$sar_file" 2>/dev/null | grep -v "^$\|Linux\|RESTART" | \
        awk -v thresh="$THRESH_MEMORY" '
        /Average/ { printf "     Average MemUsed%%: %s\n", $5; next }
        /^[0-9]/ {
            if($5+0 > thresh) { printf "     BREACH: %s - MemUsed: %s%%\n", $1, $5; count++ }
            if($5+0 > max) max=$5+0
        } END { printf "     Peak MemUsed%%: %.1f%%\n", max; if(count>0) printf "     Breaches: %d\n", count }'
        echo ""
    done

    # ---- 9c: Swap Historical ----
    echo "  [9c] Swap Usage History (sar -S)"
    echo "  -----------------------------------------------"
    for sar_file in "$sar_yesterday" "$sar_today"; do
        [[ -z "$sar_file" || ! -f "$sar_file" ]] && continue
        local day_label
        [[ "$sar_file" == *"sa${YESTERDAY}" ]] && day_label="YESTERDAY" || day_label="TODAY"
        echo "  -- ${day_label} --"
        sar -S -f "$sar_file" 2>/dev/null | grep -v "^$\|Linux\|RESTART" | \
        awk -v thresh="$THRESH_SWAP" '
        /Average/ { printf "     Average SwapUsed%%: %s\n", $5; next }
        /^[0-9]/ {
            if($5+0 > thresh) { printf "     BREACH: %s - SwapUsed: %s%%\n", $1, $5; count++ }
            if($5+0 > max) max=$5+0
        } END { printf "     Peak SwapUsed%%: %.1f%%\n", max; if(count>0) printf "     Breaches: %d\n", count }'
        echo ""
    done

    # ---- 9d: Disk I/O Historical ----
    echo "  [9d] Disk I/O History (sar -d)"
    echo "  -----------------------------------------------"
    for sar_file in "$sar_yesterday" "$sar_today"; do
        [[ -z "$sar_file" || ! -f "$sar_file" ]] && continue
        local day_label
        [[ "$sar_file" == *"sa${YESTERDAY}" ]] && day_label="YESTERDAY" || day_label="TODAY"
        echo "  -- ${day_label} --"
        sar -d -f "$sar_file" 2>/dev/null | grep -v "^$\|Linux\|RESTART" | \
        awk -v ut="$THRESH_DISK_UTIL" -v at="$THRESH_DISK_AWAIT" '
        /Average/ { printf "     Avg Dev:%-12s await:%s %%util:%s\n", $2, $(NF-1), $NF; next }
        /^[0-9]/ {
            if($NF+0 > ut) { printf "     BREACH[UTIL]: %s Dev:%-12s %%util:%s\n", $1, $2, $NF; uc++ }
            if($(NF-1)+0 > at) { printf "     BREACH[AWAIT]: %s Dev:%-12s await:%sms\n", $1, $2, $(NF-1); ac++ }
        } END { if(uc>0) printf "     Util breaches: %d\n", uc; if(ac>0) printf "     Await breaches: %d\n", ac }'
        echo ""
    done

    # ---- 9e: Network Errors ----
    echo "  [9e] Network Error Summary (sar -n EDEV)"
    echo "  -----------------------------------------------"
    for sar_file in "$sar_yesterday" "$sar_today"; do
        [[ -z "$sar_file" || ! -f "$sar_file" ]] && continue
        local day_label
        [[ "$sar_file" == *"sa${YESTERDAY}" ]] && day_label="YESTERDAY" || day_label="TODAY"
        echo "  -- ${day_label} --"
        sar -n EDEV -f "$sar_file" 2>/dev/null | grep "Average" | \
        awk '{ if($3+0>0 || $4+0>0 || $5+0>0 || $6+0>0)
            printf "     %-12s rxerr:%-6s txerr:%-6s coll:%-6s drop:%-6s\n", $2,$3,$4,$5,$6 }'
        echo ""
    done

    # ---- 9f: Consolidated Summary ----
    echo "  [9f] CONSOLIDATED 24-HOUR SUMMARY TABLE"
    echo "  ============================================================"
    printf "  %-20s %-15s %-15s %-10s\n" "METRIC" "PEAK" "THRESHOLD" "STATUS"
    echo "  ---------------------------------------------------------------"
    local summary_file="${sar_today:-$sar_yesterday}"
    if [[ -n "$summary_file" && -f "$summary_file" ]]; then
        local pk_cpu=$(sar -u -f "$summary_file" 2>/dev/null | grep -v "^$\|Linux\|Average\|RESTART" | \
            awk '{c=100-$NF; if(c>m) m=c} END{printf "%.1f",m}')
        local pk_mem=$(sar -r -f "$summary_file" 2>/dev/null | grep -v "^$\|Linux\|Average\|RESTART" | \
            awk '/^[0-9]/{if($5+0>m) m=$5+0} END{printf "%.1f",m}')
        local pk_swp=$(sar -S -f "$summary_file" 2>/dev/null | grep -v "^$\|Linux\|Average\|RESTART" | \
            awk '/^[0-9]/{if($5+0>m) m=$5+0} END{printf "%.1f",m}')

        local s1="OK"; (( $(echo "$pk_cpu > $THRESH_CPU" | bc -l 2>/dev/null || echo 0) )) && s1="BREACH"
        local s2="OK"; (( $(echo "$pk_mem > $THRESH_MEMORY" | bc -l 2>/dev/null || echo 0) )) && s2="BREACH"
        local s3="OK"; (( $(echo "$pk_swp > $THRESH_SWAP" | bc -l 2>/dev/null || echo 0) )) && s3="BREACH"

        printf "  %-20s %-15s %-15s %-10s\n" "CPU %" "${pk_cpu}%" "${THRESH_CPU}%" "$s1"
        printf "  %-20s %-15s %-15s %-10s\n" "Memory %" "${pk_mem}%" "${THRESH_MEMORY}%" "$s2"
        printf "  %-20s %-15s %-15s %-10s\n" "Swap %" "${pk_swp}%" "${THRESH_SWAP}%" "$s3"
    fi
    echo ""
}

#=============================================================================
# SECTION 10: SECURITY & VAPT AUDIT
#=============================================================================
collect_security_vapt() {
    section_header "10" "SECURITY & VAPT AUDIT"
    echo "================================================================================"

    # ---- 10a: SSH Security ----
    echo ""
    echo "  [10a] SSH Configuration Audit (/etc/ssh/sshd_config)"
    echo "  -----------------------------------------------"
    local sshd_conf="/etc/ssh/sshd_config"
    if [[ -f "$sshd_conf" ]]; then
        declare -A SSH_CHECKS=(
            ["PermitRootLogin"]="no"
            ["PasswordAuthentication"]="no"
            ["PermitEmptyPasswords"]="no"
            ["X11Forwarding"]="no"
            ["MaxAuthTries"]="4"
            ["ClientAliveInterval"]="300"
            ["ClientAliveCountMax"]="3"
            ["Protocol"]="2"
            ["LoginGraceTime"]="60"
            ["AllowAgentForwarding"]="no"
            ["Banner"]="/etc/issue.net"
        )

        printf "     %-30s %-15s %-15s %-10s\n" "PARAMETER" "CURRENT" "EXPECTED" "STATUS"
        echo "     -----------------------------------------------------------------------"

        for param in "${!SSH_CHECKS[@]}"; do
            local expected="${SSH_CHECKS[$param]}"
            local current
            current=$(grep -i "^${param}" "$sshd_conf" 2>/dev/null | tail -1 | awk '{print $2}')
            if [[ -z "$current" ]]; then
                current="(default)"
            fi

            local status="OK"
            if [[ "$current" == "(default)" ]]; then
                status="REVIEW"
                log_alert "WARNING" "SSH-CONFIG" "SSH ${param} not explicitly set (using default)" \
                    "Explicitly set ${param} ${expected} in sshd_config for compliance."
            elif [[ "$current" != "$expected" ]]; then
                status="NON-COMPLIANT"
                log_alert "CRITICAL" "SSH-SECURITY" "SSH ${param}=${current} (expected: ${expected})" \
                    "VAPT Finding: Set ${param} to ${expected} in /etc/ssh/sshd_config and restart sshd."
            fi
            printf "     %-30s %-15s %-15s %-10s\n" "$param" "$current" "$expected" "$status"
        done

        # Weak cipher check
        echo ""
        echo "  >> Weak Cipher/MAC Check:"
        local weak_ciphers="3des-cbc arcfour blowfish-cbc cast128-cbc"
        local configured_ciphers
        configured_ciphers=$(grep -i "^Ciphers" "$sshd_conf" 2>/dev/null | awk '{print $2}')
        if [[ -z "$configured_ciphers" ]]; then
            echo "     Ciphers not explicitly restricted (uses system defaults) - REVIEW NEEDED"
            log_alert "WARNING" "SSH-CIPHERS" "SSH Ciphers not explicitly restricted in sshd_config" \
                "Define strong cipher list in sshd_config. Remove CBC mode ciphers per VAPT requirements."
        else
            local found_weak=0
            for wc in $weak_ciphers; do
                if echo "$configured_ciphers" | grep -qi "$wc"; then
                    echo "     *** WEAK CIPHER FOUND: ${wc} ***"
                    found_weak=1
                fi
            done
            (( found_weak == 0 )) && echo "     No weak ciphers in configuration."
        fi
    else
        echo "     /etc/ssh/sshd_config not found."
    fi

    # ---- 10b: Failed Login / Brute Force ----
    echo ""
    echo "  [10b] Failed Login Analysis (last 24 hours)"
    echo "  -----------------------------------------------"
    local secure_log="/var/log/secure"
    [[ ! -f "$secure_log" ]] && secure_log="/var/log/auth.log"

    if [[ -f "$secure_log" ]]; then
        local yesterday_date=$(date -d "yesterday" '+%b %e')
        local today_date=$(date '+%b %e')

        local total_failures
        total_failures=$(grep -cE "Failed password|authentication failure" "$secure_log" 2>/dev/null || echo 0)
        echo "     Total failed login attempts (in log): ${total_failures}"

        echo ""
        echo "     Top Source IPs with Failed Logins:"
        printf "     %-20s %-10s %s\n" "SOURCE IP" "ATTEMPTS" "STATUS"
        echo "     ------------------------------------------------"
        grep "Failed password" "$secure_log" 2>/dev/null | \
            grep -oE "([0-9]{1,3}\.){3}[0-9]{1,3}" | sort | uniq -c | sort -rn | head -10 | \
            while read count ip; do
                local status="OK"
                if (( count >= THRESH_FAILED_LOGIN )); then
                    status="BRUTE-FORCE?"
                    log_alert "CRITICAL" "BRUTE-FORCE" "IP ${ip} has ${count} failed login attempts" \
                        "Potential brute force attack from ${ip}. Block via firewall. Notify Security team."
                fi
                printf "     %-20s %-10s %s\n" "$ip" "$count" "$status"
            done

        echo ""
        echo "     Failed Login Usernames (top 10):"
        grep "Failed password" "$secure_log" 2>/dev/null | \
            grep -oP "for (invalid user )?\K\S+" | sort | uniq -c | sort -rn | head -10 | \
            while read count user; do
                printf "     %-20s %s attempts\n" "$user" "$count"
            done

        # Locked accounts
        echo ""
        echo "     Locked Accounts (pam_faillock):"
        if check_command faillock; then
            local locked_users
            locked_users=$(faillock --dir /var/run/faillock 2>/dev/null | grep -v "^$\|When" | awk '{print $1}' | sort -u)
            if [[ -n "$locked_users" ]]; then
                echo "$locked_users" | while read u; do
                    echo "     *** LOCKED: ${u} ***"
                    log_alert "WARNING" "ACCOUNT-LOCKED" "Account '${u}' is locked by faillock" \
                        "Verify if legitimate lockout. Unlock with: faillock --user ${u} --reset"
                done
            else
                echo "     No accounts currently locked."
            fi
        else
            echo "     faillock command not available."
        fi
    else
        echo "     Secure log not found at /var/log/secure or /var/log/auth.log"
    fi

    # ---- 10c: User & Privilege Audit ----
    echo ""
    echo "  [10c] User & Privilege Audit"
    echo "  -----------------------------------------------"

    # UID 0 accounts
    echo "     UID 0 Accounts (should only be root):"
    local uid0_users
    uid0_users=$(awk -F: '$3==0 {print $1}' /etc/passwd)
    echo "$uid0_users" | while read u; do
        if [[ "$u" != "root" ]]; then
            echo "     *** NON-COMPLIANT: ${u} has UID 0 ***"
            log_alert "CRITICAL" "UID0-USER" "Non-root account '${u}' has UID 0" \
                "VAPT Critical: Remove UID 0 from account '${u}'. Only root should have UID 0."
        else
            echo "     root (expected)"
        fi
    done

    # Empty password accounts
    echo ""
    echo "     Accounts with Empty Passwords:"
    local empty_pw
    empty_pw=$(awk -F: '($2=="" || $2=="!!" || $2=="!") && $1!="*" {print $1}' /etc/shadow 2>/dev/null)
    if [[ -n "$empty_pw" ]]; then
        echo "$empty_pw" | while read u; do
            echo "     *** ${u} - EMPTY/NO PASSWORD ***"
            log_alert "CRITICAL" "EMPTY-PASSWORD" "Account '${u}' has empty or no password" \
                "VAPT Critical: Set strong password for account '${u}' immediately."
        done
    else
        echo "     None found."
    fi

    # Accounts with no expiry
    echo ""
    echo "     Accounts with No Password Expiry (non-system, UID>=1000):"
    awk -F: '$3>=1000 && $1!="nobody" && $1!="nfsnobody" {print $1}' /etc/passwd 2>/dev/null | while read u; do
        local max_days
        max_days=$(chage -l "$u" 2>/dev/null | grep "Maximum" | awk -F: '{print $2}' | tr -d ' ')
        if [[ "$max_days" == "99999" || "$max_days" == "-1" || "$max_days" == "never" ]]; then
            printf "     %-20s Max Days: %-10s *** NO EXPIRY ***\n" "$u" "$max_days"
            log_alert "WARNING" "PASSWORD-EXPIRY" "Account '${u}' has no password expiry (max_days: ${max_days})" \
                "Set password expiry: chage -M ${CIS_PASS_MAX_DAYS} ${u}"
        fi
    done

    # NOPASSWD in sudoers
    echo ""
    echo "     NOPASSWD Entries in Sudoers:"
    local nopasswd_entries
    nopasswd_entries=$(grep -rh "NOPASSWD" /etc/sudoers /etc/sudoers.d/ 2>/dev/null | grep -v "^#")
    if [[ -n "$nopasswd_entries" ]]; then
        echo "$nopasswd_entries" | while read line; do
            echo "     *** ${line} ***"
        done
        log_alert "WARNING" "SUDOERS-NOPASSWD" "NOPASSWD entries found in sudoers configuration" \
            "VAPT Finding: Remove NOPASSWD from sudoers. All sudo must require password for audit compliance."
    else
        echo "     None found (compliant)."
    fi

    # Orphan users (UID>=1000, no valid home)
    echo ""
    echo "     Orphan Users (no home directory):"
    awk -F: '$3>=1000 && $1!="nobody" && $1!="nfsnobody" {print $1":"$6}' /etc/passwd 2>/dev/null | while IFS=: read u home; do
        if [[ ! -d "$home" ]]; then
            printf "     %-20s Home: %-30s *** MISSING ***\n" "$u" "$home"
            log_alert "WARNING" "ORPHAN-USER" "User '${u}' home directory '${home}' does not exist" \
                "Review account '${u}'. Remove if unused: userdel ${u}"
        fi
    done

    # Recently modified passwd/shadow
    echo ""
    echo "     Recently Modified Auth Files (last 7 days):"
    for f in /etc/passwd /etc/shadow /etc/group /etc/gshadow /etc/sudoers; do
        if [[ -f "$f" ]]; then
            local mod_days
            mod_days=$(( ($(date +%s) - $(stat -c %Y "$f")) / 86400 ))
            if (( mod_days <= 7 )); then
                printf "     %-30s Modified: %d days ago\n" "$f" "$mod_days"
                log_alert "INFO" "AUTH-FILE-MOD" "${f} was modified ${mod_days} day(s) ago" \
                    "Verify recent changes to ${f} are authorized."
            fi
        fi
    done

    # ---- 10d: SUID/SGID Binary Audit ----
    echo ""
    echo "  [10d] SUID/SGID Binary Audit"
    echo "  -----------------------------------------------"

    # Standard allowed SUID paths
    local allowed_suid_dirs="/usr/bin /usr/sbin /usr/lib /usr/lib64 /usr/libexec /bin /sbin"

    echo "     SUID files outside standard paths:"
    local suspicious_suid=0
    find / -perm -4000 -type f 2>/dev/null | while read f; do
        local in_allowed=0
        for d in $allowed_suid_dirs; do
            [[ "$f" == "$d"/* ]] && in_allowed=1 && break
        done
        if (( in_allowed == 0 )); then
            local owner=$(stat -c '%U:%G' "$f" 2>/dev/null)
            local perms=$(stat -c '%a' "$f" 2>/dev/null)
            printf "     *** SUSPICIOUS: %-40s Owner:%-15s Perms:%s\n" "$f" "$owner" "$perms"
            log_alert "CRITICAL" "SUID-SUSPICIOUS" "Suspicious SUID binary: ${f} (owner: ${owner})" \
                "VAPT Critical: Investigate SUID binary ${f}. Remove SUID if not required: chmod u-s ${f}"
            suspicious_suid=1
        fi
    done
    (( suspicious_suid == 0 )) && echo "     No suspicious SUID files found outside standard paths."

    echo ""
    echo "     SGID files outside standard paths:"
    local suspicious_sgid=0
    find / -perm -2000 -type f 2>/dev/null | while read f; do
        local in_allowed=0
        for d in $allowed_suid_dirs; do
            [[ "$f" == "$d"/* ]] && in_allowed=1 && break
        done
        if (( in_allowed == 0 )); then
            printf "     *** SUSPICIOUS SGID: %s\n" "$f"
            suspicious_sgid=1
        fi
    done
    (( suspicious_sgid == 0 )) && echo "     No suspicious SGID files found."

    # ---- 10e: World-Writable Files & Dirs ----
    echo ""
    echo "  [10e] World-Writable Files & Directories"
    echo "  -----------------------------------------------"

    echo "     World-writable directories without sticky bit:"
    find / -path /proc -prune -o -path /sys -prune -o -path /dev -prune -o \
        -type d -perm -0002 ! -perm -1000 -print 2>/dev/null | head -20 | while read d; do
        printf "     *** %s ***\n" "$d"
        log_alert "WARNING" "WORLD-WRITABLE" "World-writable dir without sticky bit: ${d}" \
            "Set sticky bit: chmod +t ${d} (or restrict permissions)"
    done

    echo ""
    echo "     World-writable files in critical paths:"
    for dir in /etc /usr /var /opt; do
        find "$dir" -type f -perm -0002 2>/dev/null | head -5 | while read f; do
            printf "     *** %s ***\n" "$f"
            log_alert "CRITICAL" "WORLD-WRITABLE-FILE" "World-writable file in critical path: ${f}" \
                "VAPT Finding: Remove world-write: chmod o-w ${f}"
        done
    done

    # ---- 10f: Firewall & SELinux Status ----
    echo ""
    echo "  [10f] Firewall & SELinux Status"
    echo "  -----------------------------------------------"

    # Firewall
    echo "     Firewall Status:"
    if check_command firewall-cmd; then
        local fw_state
        fw_state=$(firewall-cmd --state 2>/dev/null)
        printf "     firewalld: %s\n" "$fw_state"
        if [[ "$fw_state" != "running" ]]; then
            log_alert "CRITICAL" "FIREWALL" "firewalld is NOT running" \
                "VAPT Critical: Enable firewalld: systemctl enable --now firewalld"
        fi
        echo "     Active zones:"
        firewall-cmd --get-active-zones 2>/dev/null | sed 's/^/       /'
    elif check_command iptables; then
        local rule_count
        rule_count=$(iptables -L -n 2>/dev/null | grep -c "^[A-Z]")
        printf "     iptables rules: %d\n" "$rule_count"
        if (( rule_count < 3 )); then
            log_alert "WARNING" "FIREWALL" "iptables has very few rules (${rule_count})" \
                "Review firewall configuration. Minimal rules may indicate no protection."
        fi
    else
        echo "     No firewall tool detected."
        log_alert "CRITICAL" "FIREWALL" "No firewall (firewalld/iptables) detected" \
            "VAPT Critical: Install and configure firewall immediately."
    fi

    # SELinux
    echo ""
    echo "     SELinux Status:"
    local selinux_mode
    selinux_mode=$(getenforce 2>/dev/null || echo "Not Installed")
    printf "     Mode: %s\n" "$selinux_mode"
    if [[ "$selinux_mode" == "Disabled" || "$selinux_mode" == "Permissive" ]]; then
        log_alert "CRITICAL" "SELINUX" "SELinux is ${selinux_mode} (should be Enforcing)" \
            "VAPT Critical: Set SELinux to Enforcing: setenforce 1 && sed -i 's/SELINUX=.*/SELINUX=enforcing/' /etc/selinux/config"
    fi

    # SELinux denials in last 24h
    if [[ -f /var/log/audit/audit.log ]]; then
        local denial_count
        denial_count=$(grep "type=AVC.*denied" /var/log/audit/audit.log 2>/dev/null | \
            awk -v cutoff=$(date -d "24 hours ago" +%s) '{
                match($0, /msg=audit\(([0-9]+)/, a);
                if(a[1]+0 >= cutoff) count++
            } END{print count+0}')
        printf "     SELinux Denials (24h): %s\n" "$denial_count"
        if (( denial_count > 50 )); then
            log_alert "WARNING" "SELINUX-DENIALS" "${denial_count} SELinux denials in last 24h" \
                "High SELinux denial count. Review with: ausearch -m AVC -ts recent | audit2why"
        fi
    fi

    # ---- 10g: Open Ports & Listening Services ----
    echo ""
    echo "  [10g] Open Ports & Listening Services"
    echo "  -----------------------------------------------"
    if check_command ss; then
        printf "     %-8s %-25s %-25s %s\n" "PROTO" "LOCAL ADDRESS" "STATE" "PROCESS"
        echo "     -----------------------------------------------------------------------"
        ss -tulnp 2>/dev/null | grep LISTEN | while read proto recvq sendq local_addr peer_addr state process; do
            # Some ss versions have different column orders
            if [[ "$state" == "LISTEN" ]] || [[ "$local_addr" == *":"* ]]; then
                local proc_name
                proc_name=$(echo "$process" | grep -oP 'users:\(\("\K[^"]+' || echo "$process")
                printf "     %-8s %-25s %-25s %s\n" "$proto" "$local_addr" "LISTEN" "${proc_name:0:30}"
            fi
        done
    elif check_command netstat; then
        netstat -tulnp 2>/dev/null | grep LISTEN | head -30 | sed 's/^/     /'
    fi

    # Count listening ports
    local port_count
    port_count=$(ss -tulnp 2>/dev/null | grep -c LISTEN || echo 0)
    echo ""
    printf "     Total listening ports: %d\n" "$port_count"

    # ---- 10h: Certificate Expiry Check ----
    echo ""
    echo "  [10h] SSL/TLS Certificate Expiry Check"
    echo "  -----------------------------------------------"

    if check_command openssl; then
        local cert_found=0
        for cert_dir in $CERT_SCAN_PATHS; do
            [[ ! -d "$cert_dir" ]] && continue
            find "$cert_dir" -type f \( -name "*.pem" -o -name "*.crt" -o -name "*.cert" \) 2>/dev/null | while read cert; do
                local expiry_date expiry_epoch days_left
                expiry_date=$(openssl x509 -enddate -noout -in "$cert" 2>/dev/null | cut -d= -f2)
                [[ -z "$expiry_date" ]] && continue
                expiry_epoch=$(date -d "$expiry_date" +%s 2>/dev/null)
                [[ -z "$expiry_epoch" ]] && continue
                days_left=$(( (expiry_epoch - $(date +%s)) / 86400 ))
                cert_found=1

                local status="OK"
                if (( days_left < 0 )); then
                    status="EXPIRED"
                    log_alert "CRITICAL" "CERT-EXPIRED" "Certificate EXPIRED: ${cert} (expired ${days_left#-} days ago)" \
                        "IMMEDIATE: Renew expired certificate ${cert}. Notify Application/Security team."
                elif (( days_left <= THRESH_CERT_CRIT_DAYS )); then
                    status="CRITICAL"
                    log_alert "CRITICAL" "CERT-EXPIRING" "Certificate expiring in ${days_left} days: ${cert}" \
                        "Renew certificate within ${days_left} days. Notify Application team."
                elif (( days_left <= THRESH_CERT_WARN_DAYS )); then
                    status="WARNING"
                    log_alert "WARNING" "CERT-EXPIRING" "Certificate expiring in ${days_left} days: ${cert}" \
                        "Plan certificate renewal for ${cert}."
                fi

                if [[ "$status" != "OK" ]]; then
                    local cn
                    cn=$(openssl x509 -subject -noout -in "$cert" 2>/dev/null | sed 's/.*CN\s*=\s*//')
                    printf "     %-50s CN:%-20s Days:%d [%s]\n" "${cert:0:50}" "${cn:0:20}" "$days_left" "$status"
                fi
            done
        done
        (( cert_found == 0 )) && echo "     No certificates found in scan paths."
    else
        echo "     [SKIPPED] openssl not available"
    fi

    # ---- 10i: Password Policy Compliance ----
    echo ""
    echo "  [10i] Password Policy Compliance"
    echo "  -----------------------------------------------"

    echo "     /etc/login.defs Check:"
    if [[ -f /etc/login.defs ]]; then
        declare -A LOGIN_DEFS_CHECKS=(
            ["PASS_MAX_DAYS"]="$CIS_PASS_MAX_DAYS"
            ["PASS_MIN_DAYS"]="$CIS_PASS_MIN_DAYS"
            ["PASS_MIN_LEN"]="$CIS_PASS_MIN_LEN"
            ["PASS_WARN_AGE"]="$CIS_PASS_WARN_AGE"
        )

        printf "     %-20s %-10s %-10s %-10s\n" "PARAMETER" "CURRENT" "CIS REQ" "STATUS"
        echo "     -----------------------------------------------------------"
        for param in PASS_MAX_DAYS PASS_MIN_DAYS PASS_MIN_LEN PASS_WARN_AGE; do
            local current expected status
            current=$(grep "^${param}" /etc/login.defs 2>/dev/null | awk '{print $2}')
            expected="${LOGIN_DEFS_CHECKS[$param]}"
            [[ -z "$current" ]] && current="(not set)"

            if [[ "$current" == "(not set)" ]]; then
                status="MISSING"
            elif [[ "$param" == "PASS_MAX_DAYS" ]] && (( current > expected )); then
                status="NON-COMPLIANT"
            elif [[ "$param" == "PASS_MIN_DAYS" ]] && (( current < expected )); then
                status="NON-COMPLIANT"
            elif [[ "$param" == "PASS_MIN_LEN" ]] && (( current < expected )); then
                status="NON-COMPLIANT"
            elif [[ "$param" == "PASS_WARN_AGE" ]] && (( current < expected )); then
                status="NON-COMPLIANT"
            else
                status="COMPLIANT"
            fi

            printf "     %-20s %-10s %-10s %-10s\n" "$param" "$current" "$expected" "$status"
            if [[ "$status" == "NON-COMPLIANT" || "$status" == "MISSING" ]]; then
                log_alert "WARNING" "PASSWORD-POLICY" "${param}=${current} (CIS requires ${expected})" \
                    "Update /etc/login.defs: Set ${param} to ${expected}"
            fi
        done
    fi

    # PAM password quality
    echo ""
    echo "     PAM Password Quality (pwquality):"
    local pwquality_conf="/etc/security/pwquality.conf"
    if [[ -f "$pwquality_conf" ]]; then
        for param in minlen minclass dcredit ucredit lcredit ocredit; do
            local val
            val=$(grep "^${param}" "$pwquality_conf" 2>/dev/null | awk -F= '{print $2}' | tr -d ' ')
            [[ -n "$val" ]] && printf "     %-20s = %s\n" "$param" "$val"
        done
    else
        echo "     /etc/security/pwquality.conf not found"
        log_alert "WARNING" "PWQUALITY" "pwquality.conf not configured" \
            "Configure password complexity in /etc/security/pwquality.conf per CIS benchmarks."
    fi

    # ---- 10j: Audit Daemon Health ----
    echo ""
    echo "  [10j] Audit Daemon (auditd) Health"
    echo "  -----------------------------------------------"

    local auditd_status
    auditd_status=$(systemctl is-active auditd 2>/dev/null || echo "inactive")
    local auditd_enabled
    auditd_enabled=$(systemctl is-enabled auditd 2>/dev/null || echo "disabled")

    printf "     auditd Service  : %s (enabled: %s)\n" "$auditd_status" "$auditd_enabled"

    if [[ "$auditd_status" != "active" ]]; then
        log_alert "CRITICAL" "AUDITD" "auditd is NOT running (status: ${auditd_status})" \
            "VAPT Critical: Start auditd: systemctl start auditd && systemctl enable auditd"
    fi

    if check_command auditctl; then
        local rule_count
        rule_count=$(auditctl -l 2>/dev/null | grep -cv "^No rules" || echo 0)
        printf "     Audit Rules     : %d loaded\n" "$rule_count"
        if (( rule_count < 5 )); then
            log_alert "WARNING" "AUDIT-RULES" "Only ${rule_count} audit rules loaded (expected more)" \
                "Review audit rules. Add rules for: file integrity, privilege escalation, user management."
        fi

        # Check audit log size
        if [[ -f /var/log/audit/audit.log ]]; then
            local audit_size_mb
            audit_size_mb=$(du -sm /var/log/audit/audit.log 2>/dev/null | awk '{print $1}')
            printf "     Audit Log Size  : %s MB\n" "$audit_size_mb"
        fi

        # Backlog check
        local backlog
        backlog=$(auditctl -s 2>/dev/null | grep "backlog " | awk '{print $2}')
        local backlog_limit
        backlog_limit=$(auditctl -s 2>/dev/null | grep "backlog_limit" | awk '{print $2}')
        if [[ -n "$backlog" && -n "$backlog_limit" ]]; then
            printf "     Backlog         : %s / %s\n" "$backlog" "$backlog_limit"
            if (( backlog > backlog_limit * 80 / 100 )); then
                log_alert "WARNING" "AUDIT-BACKLOG" "Audit backlog ${backlog}/${backlog_limit} (>80%)" \
                    "Audit backlog nearing limit. Increase backlog_limit or investigate event flood."
            fi
        fi
    else
        echo "     auditctl not available (install audit package)"
    fi
    echo ""
}

#=============================================================================
# SECTION 11: CIS BENCHMARK COMPLIANCE
#=============================================================================
collect_cis_compliance() {
    section_header "11" "CIS BENCHMARK COMPLIANCE CHECKS"
    echo "================================================================================"

    # ---- 11a: Kernel Security Parameters ----
    echo ""
    echo "  [11a] Kernel Security Parameters (sysctl)"
    echo "  -----------------------------------------------"
    printf "     %-50s %-10s %-10s %-10s\n" "PARAMETER" "CURRENT" "EXPECTED" "STATUS"
    echo "     ---------------------------------------------------------------------------"

    for param in "${!CIS_SYSCTL[@]}"; do
        local expected="${CIS_SYSCTL[$param]}"
        local current
        current=$(sysctl -n "$param" 2>/dev/null || echo "N/A")

        local status="COMPLIANT"
        if [[ "$current" == "N/A" ]]; then
            status="N/A"
        elif [[ "$current" != "$expected" ]]; then
            status="NON-COMPLIANT"
            log_alert "WARNING" "CIS-SYSCTL" "Kernel param ${param}=${current} (expected: ${expected})" \
                "Fix: sysctl -w ${param}=${expected} and add to /etc/sysctl.d/99-cis.conf"
        fi
        printf "     %-50s %-10s %-10s %-10s\n" "$param" "$current" "$expected" "$status"
    done

    # ---- 11b: Disabled Kernel Modules ----
    echo ""
    echo "  [11b] Disabled Kernel Modules (CIS)"
    echo "  -----------------------------------------------"
    for mod in $CIS_DISABLED_MODULES; do
        local mod_status="LOADED"
        if lsmod 2>/dev/null | grep -q "^${mod}"; then
            mod_status="LOADED *** NON-COMPLIANT ***"
            log_alert "WARNING" "CIS-MODULE" "Kernel module '${mod}' is loaded (should be disabled)" \
                "Disable: echo 'install ${mod} /bin/true' > /etc/modprobe.d/${mod}.conf && rmmod ${mod}"
        elif [[ -f "/etc/modprobe.d/${mod}.conf" ]] || grep -rq "install ${mod} /bin/true" /etc/modprobe.d/ 2>/dev/null; then
            mod_status="DISABLED (compliant)"
        else
            mod_status="NOT LOADED (no explicit disable rule)"
        fi
        printf "     %-20s : %s\n" "$mod" "$mod_status"
    done

    # ---- 11c: Filesystem Security ----
    echo ""
    echo "  [11c] Filesystem Security Checks"
    echo "  -----------------------------------------------"

    # /tmp partition
    echo "     Separate /tmp partition:"
    if mount | grep -q "on /tmp "; then
        local tmp_opts=$(mount | grep "on /tmp " | awk '{print $6}')
        echo "     /tmp is separate partition. Options: ${tmp_opts}"
        for opt in noexec nosuid nodev; do
            if ! echo "$tmp_opts" | grep -q "$opt"; then
                echo "     *** MISSING: ${opt} on /tmp ***"
                log_alert "WARNING" "CIS-TMP" "/tmp missing mount option: ${opt}" \
                    "Add ${opt} to /tmp mount options in /etc/fstab"
            fi
        done
    else
        echo "     *** /tmp is NOT a separate partition ***"
        log_alert "WARNING" "CIS-TMP" "/tmp is not a separate partition" \
            "CIS: Create separate /tmp partition with noexec,nosuid,nodev options."
    fi

    # /var/tmp
    echo ""
    echo "     /var/tmp bind mount:"
    if mount | grep -q "on /var/tmp "; then
        echo "     /var/tmp is mounted separately (compliant)"
    else
        echo "     /var/tmp not separately mounted (review needed)"
    fi

    # /dev/shm
    echo ""
    echo "     /dev/shm security:"
    local shm_opts=$(mount | grep "on /dev/shm " | awk '{print $6}')
    if [[ -n "$shm_opts" ]]; then
        echo "     /dev/shm options: ${shm_opts}"
        if ! echo "$shm_opts" | grep -q "noexec"; then
            log_alert "WARNING" "CIS-SHM" "/dev/shm missing noexec option" \
                "Add noexec,nosuid,nodev to /dev/shm in /etc/fstab"
        fi
    fi

    # Core dumps
    echo ""
    echo "     Core Dumps:"
    local core_soft=$(ulimit -Sc 2>/dev/null)
    local core_hard=$(ulimit -Hc 2>/dev/null)
    local core_sysctl=$(sysctl -n fs.suid_dumpable 2>/dev/null)
    printf "     Soft limit: %s | Hard limit: %s | suid_dumpable: %s\n" "$core_soft" "$core_hard" "$core_sysctl"
    if [[ "$core_soft" != "0" ]] || [[ "$core_sysctl" != "0" ]]; then
        log_alert "WARNING" "CIS-COREDUMP" "Core dumps not fully disabled (soft:${core_soft}, suid_dumpable:${core_sysctl})" \
            "Disable core dumps: add '* hard core 0' to /etc/security/limits.conf and set fs.suid_dumpable=0"
    fi

    # ASLR
    echo ""
    echo "     ASLR (Address Space Layout Randomization):"
    local aslr=$(sysctl -n kernel.randomize_va_space 2>/dev/null)
    printf "     kernel.randomize_va_space = %s (expected: 2)\n" "$aslr"
    if [[ "$aslr" != "2" ]]; then
        log_alert "CRITICAL" "CIS-ASLR" "ASLR not fully enabled (value: ${aslr}, expected: 2)" \
            "Enable ASLR: sysctl -w kernel.randomize_va_space=2"
    fi

    # ---- 11d: File Integrity Monitoring ----
    echo ""
    echo "  [11d] File Integrity Monitoring (AIDE/OSSEC)"
    echo "  -----------------------------------------------"

    local fim_found=0
    if check_command aide; then
        echo "     AIDE: Installed"
        local aide_db="/var/lib/aide/aide.db.gz"
        [[ -f "$aide_db" ]] && echo "     AIDE DB: ${aide_db} (exists)" || echo "     AIDE DB: NOT initialized"

        # Last AIDE check
        local aide_log="/var/log/aide/aide.log"
        if [[ -f "$aide_log" ]]; then
            local last_check
            last_check=$(stat -c '%y' "$aide_log" 2>/dev/null | cut -d. -f1)
            echo "     Last Check: ${last_check}"
        fi
        fim_found=1
    else
        echo "     AIDE: NOT installed"
    fi

    if check_command ossec-control || [[ -d "/var/ossec" ]]; then
        echo "     OSSEC: Installed"
        fim_found=1
    fi

    if (( fim_found == 0 )); then
        echo "     *** No File Integrity Monitoring tool detected ***"
        log_alert "CRITICAL" "CIS-FIM" "No File Integrity Monitoring (AIDE/OSSEC) installed" \
            "VAPT Critical: Install AIDE: yum install aide && aide --init && aide --check"
    fi

    # ---- 11e: Umask Validation ----
    echo ""
    echo "  [11e] System Umask Validation"
    echo "  -----------------------------------------------"

    for f in /etc/profile /etc/bashrc /etc/login.defs; do
        if [[ -f "$f" ]]; then
            local umask_val
            umask_val=$(grep -i "^umask\|^[[:space:]]*umask" "$f" 2>/dev/null | tail -1 | awk '{print $2}')
            if [[ -n "$umask_val" ]]; then
                local status="COMPLIANT"
                # Check if umask is restrictive enough (027 or 077)
                if [[ "$umask_val" != "027" && "$umask_val" != "077" && "$umask_val" != "0027" && "$umask_val" != "0077" ]]; then
                    status="NON-COMPLIANT"
                    log_alert "WARNING" "CIS-UMASK" "Umask in ${f} is ${umask_val} (expected: ${CIS_UMASK} or stricter)" \
                        "Set umask to ${CIS_UMASK} in ${f}"
                fi
                printf "     %-25s umask: %-8s [%s]\n" "$f" "$umask_val" "$status"
            else
                printf "     %-25s umask: (not set)\n" "$f"
            fi
        fi
    done
    echo ""
}

#=============================================================================
# SECTION 12: INFRASTRUCTURE & OPERATIONAL CHECKS
# (Excludes: Time sync, Bonding/Teaming, Multipath - vSphere managed)
#=============================================================================
collect_infra_checks() {
    section_header "12" "INFRASTRUCTURE & OPERATIONAL CHECKS"
    echo "================================================================================"

    # ---- 12a: Zombie & Defunct Processes ----
    echo ""
    echo "  [12a] Zombie & Defunct Processes"
    echo "  -----------------------------------------------"
    local zombie_count
    zombie_count=$(ps aux | awk '$8~/^Z/' | wc -l)
    printf "     Zombie process count: %d (threshold: %d)\n" "$zombie_count" "$THRESH_ZOMBIE"

    if (( zombie_count > 0 )); then
        echo "     Zombie processes:"
        printf "     %-8s %-8s %-10s %s\n" "PID" "PPID" "USER" "COMMAND"
        ps aux | awk '$8~/^Z/' | while read user pid cpu mem vsz rss tty stat start time cmd; do
            local ppid
            ppid=$(ps -o ppid= -p "$pid" 2>/dev/null | tr -d ' ')
            printf "     %-8s %-8s %-10s %s\n" "$pid" "$ppid" "$user" "${cmd:0:50}"
        done
        if (( zombie_count > THRESH_ZOMBIE )); then
            log_alert "WARNING" "ZOMBIE" "${zombie_count} zombie processes detected (threshold: ${THRESH_ZOMBIE})" \
                "Investigate parent processes. Notify Application team if app-related."
        fi
    fi

    # ---- 12b: Kernel & Pending Reboot ----
    echo ""
    echo "  [12b] Kernel & Pending Reboot Check"
    echo "  -----------------------------------------------"
    local running_kernel=$(uname -r)
    local installed_kernel
    installed_kernel=$(rpm -q kernel --last 2>/dev/null | head -1 | awk '{print $1}' | sed 's/kernel-//')

    printf "     Running Kernel  : %s\n" "$running_kernel"
    printf "     Latest Installed: %s\n" "${installed_kernel:-N/A}"

    if [[ -n "$installed_kernel" && "$running_kernel" != "$installed_kernel" ]]; then
        echo "     *** REBOOT PENDING - Kernel mismatch ***"
        log_alert "WARNING" "REBOOT-PENDING" "Running kernel (${running_kernel}) differs from installed (${installed_kernel})" \
            "System reboot required for new kernel. Schedule maintenance window."
    else
        echo "     Kernel is current (no reboot pending)."
    fi

    # needs-restarting check
    if check_command needs-restarting; then
        local restart_needed
        restart_needed=$(needs-restarting -r 2>/dev/null; echo $?)
        if [[ "$restart_needed" == "1" ]]; then
            echo "     needs-restarting: REBOOT RECOMMENDED"
            log_alert "WARNING" "NEEDS-RESTART" "System requires reboot (needs-restarting detected)" \
                "Schedule reboot during maintenance window."
        fi

        echo ""
        echo "     Services needing restart:"
        needs-restarting -s 2>/dev/null | head -10 | sed 's/^/     /'
    fi

    # ---- 12c: Package Security Errata ----
    echo ""
    echo "  [12c] Available Security Updates"
    echo "  -----------------------------------------------"

    if check_command yum; then
        local sec_updates
        sec_updates=$(yum updateinfo list security 2>/dev/null | grep -c "/Sec\." || echo "N/A")
        printf "     Pending security updates: %s\n" "$sec_updates"
        if [[ "$sec_updates" != "N/A" ]] && (( sec_updates > 0 )); then
            log_alert "WARNING" "SECURITY-PATCHES" "${sec_updates} security updates available" \
                "Apply security patches: yum update --security. Coordinate with Change Management."
            echo "     Critical/Important (top 10):"
            yum updateinfo list security 2>/dev/null | grep -iE "Critical|Important" | head -10 | sed 's/^/       /'
        fi
    elif check_command dnf; then
        local sec_updates
        sec_updates=$(dnf updateinfo list --security 2>/dev/null | grep -c "Sec\." || echo "N/A")
        printf "     Pending security updates: %s\n" "$sec_updates"
        if [[ "$sec_updates" != "N/A" ]] && (( sec_updates > 0 )); then
            log_alert "WARNING" "SECURITY-PATCHES" "${sec_updates} security updates available" \
                "Apply security patches: dnf update --security"
        fi
    fi

    # ---- 12d: DNS Resolution Health ----
    echo ""
    echo "  [12d] DNS Resolution Health"
    echo "  -----------------------------------------------"

    echo "     Nameservers configured:"
    grep "^nameserver" /etc/resolv.conf 2>/dev/null | while read _ ns; do
        # Test each nameserver
        local dns_result
        dns_result=$(timeout 5 nslookup "$(hostname)" "$ns" 2>/dev/null)
        if [[ $? -eq 0 ]]; then
            printf "     %-20s : RESPONSIVE\n" "$ns"
        else
            printf "     %-20s : *** FAILED ***\n" "$ns"
            log_alert "WARNING" "DNS" "Nameserver ${ns} not responding" \
                "DNS resolution failure for ${ns}. Update /etc/resolv.conf or notify Network team."
        fi
    done

    # ---- 12e: Backup Agent Check ----
    echo ""
    echo "  [12e] Backup Agent Status"
    echo "  -----------------------------------------------"

    local backup_found=0
    local backup_procs
    backup_procs=$(ps aux | grep -E "${BACKUP_AGENTS}" | grep -v grep)
    if [[ -n "$backup_procs" ]]; then
        echo "$backup_procs" | while read user pid cpu mem vsz rss tty stat start time cmd; do
            printf "     %-10s PID:%-8s %s\n" "$user" "$pid" "${cmd:0:60}"
        done
        backup_found=1
    fi

    if (( backup_found == 0 )); then
        echo "     *** No backup agent processes detected ***"
        log_alert "WARNING" "BACKUP-AGENT" "No backup agent processes running" \
            "Verify backup agent is installed and running. Notify Backup team."
    fi

    # ---- 12f: Failed Systemd Units ----
    echo ""
    echo "  [12f] Failed Systemd Units"
    echo "  -----------------------------------------------"
    local failed_units
    failed_units=$(systemctl --failed --no-legend 2>/dev/null)
    if [[ -n "$failed_units" ]]; then
        echo "$failed_units" | while read unit load active sub desc; do
            printf "     *** FAILED: %-40s (%s)\n" "$unit" "$sub"
            log_alert "WARNING" "SYSTEMD-FAILED" "Systemd unit '${unit}' is in failed state" \
                "Investigate: journalctl -u ${unit}. Restart if applicable."
        done
    else
        echo "     No failed systemd units."
    fi

    # ---- 12g: Kdump Status ----
    echo ""
    echo "  [12g] Kdump (Crash Dump) Status"
    echo "  -----------------------------------------------"
    local kdump_status
    kdump_status=$(systemctl is-active kdump 2>/dev/null || echo "inactive")
    local kdump_enabled
    kdump_enabled=$(systemctl is-enabled kdump 2>/dev/null || echo "disabled")
    printf "     kdump: %s (enabled: %s)\n" "$kdump_status" "$kdump_enabled"

    if [[ "$kdump_status" != "active" ]]; then
        log_alert "WARNING" "KDUMP" "kdump is not active (status: ${kdump_status})" \
            "Enable kdump for crash analysis: systemctl enable --now kdump"
    fi

    # Check crash directory
    local crash_dir="/var/crash"
    if [[ -d "$crash_dir" ]]; then
        local crash_count
        crash_count=$(find "$crash_dir" -mindepth 1 -maxdepth 1 -type d 2>/dev/null | wc -l)
        if (( crash_count > 0 )); then
            echo "     *** ${crash_count} crash dump(s) found in ${crash_dir} ***"
            find "$crash_dir" -mindepth 1 -maxdepth 1 -type d 2>/dev/null | while read d; do
                printf "     Crash: %s (%s)\n" "$(basename "$d")" "$(stat -c '%y' "$d" 2>/dev/null | cut -d. -f1)"
            done
            log_alert "WARNING" "CRASH-DUMPS" "${crash_count} crash dump(s) found in ${crash_dir}" \
                "Analyze crash dumps for root cause. Engage vendor/application team."
        fi
    fi

    # ---- 12h: Core Dump Detection ----
    echo ""
    echo "  [12h] Recent Core Dumps"
    echo "  -----------------------------------------------"
    if check_command coredumpctl; then
        local recent_cores
        recent_cores=$(coredumpctl list --since "24 hours ago" 2>/dev/null | grep -c "^\|present" || echo 0)
        if (( recent_cores > 0 )); then
            echo "     *** ${recent_cores} core dump(s) in last 24 hours ***"
            coredumpctl list --since "24 hours ago" 2>/dev/null | tail -10 | sed 's/^/     /'
            log_alert "WARNING" "CORE-DUMPS" "${recent_cores} core dumps detected in last 24h" \
                "Application crashes detected. Notify Application team for analysis."
        else
            echo "     No core dumps in last 24 hours."
        fi
    else
        # Fallback: check traditional locations
        local core_files
        core_files=$(find /var/crash /var/lib/systemd/coredump /tmp -name "core.*" -o -name "core" -mtime -1 2>/dev/null | wc -l)
        printf "     Core files found (last 24h): %d\n" "$core_files"
    fi

    # ---- 12i: Log Rotation & Oversized Logs ----
    echo ""
    echo "  [12i] Log Rotation & Oversized Logs"
    echo "  -----------------------------------------------"

    # Logrotate last run
    local logrotate_status
    if [[ -f /var/lib/logrotate/logrotate.status ]]; then
        local last_rotate
        last_rotate=$(stat -c '%y' /var/lib/logrotate/logrotate.status 2>/dev/null | cut -d. -f1)
        echo "     Last logrotate: ${last_rotate}"
    else
        echo "     logrotate status file not found"
        log_alert "WARNING" "LOGROTATE" "logrotate status file missing" \
            "Verify logrotate is configured and running."
    fi

    echo ""
    echo "     Oversized log files (>${THRESH_LOG_SIZE_MB}MB):"
    local oversized=0
    find /var/log -type f -size +${THRESH_LOG_SIZE_MB}M 2>/dev/null | while read f; do
        local size_mb
        size_mb=$(du -sm "$f" 2>/dev/null | awk '{print $1}')
        printf "     *** %-50s %s MB\n" "$f" "$size_mb"
        log_alert "WARNING" "OVERSIZED-LOG" "Log file ${f} is ${size_mb}MB (>${THRESH_LOG_SIZE_MB}MB)" \
            "Check logrotate config for ${f}. May need manual cleanup or rotation."
        oversized=1
    done
    (( oversized == 0 )) && echo "     No oversized logs found."
    echo ""
}

#=============================================================================
# SECTION 13: PATCHING & COMPLIANCE STATUS
#=============================================================================
collect_patching_status() {
    section_header "13" "PATCHING & COMPLIANCE STATUS"
    echo "================================================================================"

    # Last patching date
    echo ""
    echo "  [13a] Last Patching Activity"
    echo "  -----------------------------------------------"
    if check_command yum; then
        local last_patch_date
        last_patch_date=$(yum history list 2>/dev/null | awk 'NR==4{print $4,$5,$6}')
        echo "     Last yum transaction: ${last_patch_date:-N/A}"

        # Calculate days since last patch
        if [[ -n "$last_patch_date" ]]; then
            local patch_epoch
            patch_epoch=$(date -d "$last_patch_date" +%s 2>/dev/null)
            if [[ -n "$patch_epoch" ]]; then
                local days_since=$(( ($(date +%s) - patch_epoch) / 86400 ))
                printf "     Days since last patch: %d (threshold: %d)\n" "$days_since" "$THRESH_PATCH_DAYS"
                if (( days_since > THRESH_PATCH_DAYS )); then
                    log_alert "WARNING" "PATCHING" "Last patch was ${days_since} days ago (threshold: ${THRESH_PATCH_DAYS})" \
                        "System is overdue for patching. Schedule patching via Red Hat Satellite."
                fi
            fi
        fi

        echo ""
        echo "     Recent yum history (last 5):"
        yum history list 2>/dev/null | head -8 | sed 's/^/     /'
    fi

    # Red Hat Satellite registration
    echo ""
    echo "  [13b] Satellite/Subscription Status"
    echo "  -----------------------------------------------"
    if check_command subscription-manager; then
        local sub_status
        sub_status=$(subscription-manager status 2>/dev/null | grep "Overall Status" | awk -F: '{print $2}' | tr -d ' ')
        printf "     Subscription Status: %s\n" "${sub_status:-N/A}"
        if [[ "$sub_status" != "Current" && -n "$sub_status" ]]; then
            log_alert "WARNING" "SUBSCRIPTION" "System subscription status: ${sub_status}" \
                "System may not be receiving updates. Check subscription-manager."
        fi
    else
        echo "     subscription-manager not available"
    fi

    # Compliance summary
    echo ""
    echo "  [13c] Compliance Summary"
    echo "  -----------------------------------------------"

    local total_findings critical_findings warning_findings
    total_findings=$(wc -l < "${ALERT_LOG}" 2>/dev/null || echo 0)
    critical_findings=$(grep -c "^CRITICAL" "${ALERT_LOG}" 2>/dev/null || echo 0)
    warning_findings=$(grep -c "^WARNING" "${ALERT_LOG}" 2>/dev/null || echo 0)

    echo "     ========================================="
    echo "     TOTAL FINDINGS    : ${total_findings}"
    echo "     CRITICAL          : ${critical_findings}"
    echo "     WARNING           : ${warning_findings}"
    echo "     ========================================="

    if (( critical_findings > 0 )); then
        echo "     STATUS: *** NON-COMPLIANT - CRITICAL FINDINGS ***"
    elif (( warning_findings > 0 )); then
        echo "     STATUS: PARTIALLY COMPLIANT - WARNINGS PRESENT"
    else
        echo "     STATUS: COMPLIANT - ALL CHECKS PASSED"
    fi
    echo ""
}

#=============================================================================
# SECTION 14: ALERT SUMMARY & RECOMMENDATIONS
#=============================================================================
generate_recommendations() {
    section_header "14" "ALERT SUMMARY & RECOMMENDATIONS"
    echo "================================================================================"
    echo ""

    if [[ ! -s "${ALERT_LOG}" ]]; then
        echo "  **********************************************"
        echo "  * ALL SYSTEMS HEALTHY - NO BREACHES FOUND   *"
        echo "  **********************************************"
        echo ""
        return
    fi

    local critical_count warning_count info_count
    critical_count=$(grep -c "^CRITICAL" "${ALERT_LOG}" 2>/dev/null || echo 0)
    warning_count=$(grep -c "^WARNING" "${ALERT_LOG}" 2>/dev/null || echo 0)
    info_count=$(grep -c "^INFO" "${ALERT_LOG}" 2>/dev/null || echo 0)

    echo "  Overall: ${critical_count} CRITICAL | ${warning_count} WARNING | ${info_count} INFO"
    echo ""

    # Findings table
    local seq_num=1
    printf "  %-4s %-10s %-18s %s\n" "#" "SEVERITY" "COMPONENT" "FINDING"
    echo "  ========================================================================================"

    while IFS='|' read -r severity component message recommendation; do
        printf "  %-4s %-10s %-18s %s\n" "$seq_num" "$severity" "$component" "${message:0:70}"
        seq_num=$((seq_num + 1))
    done < "${ALERT_LOG}"

    # Recommendations
    echo ""
    echo "  RECOMMENDATIONS:"
    echo "  ========================================================================================"
    seq_num=1
    while IFS='|' read -r severity component message recommendation; do
        printf "  %d. [%s][%s] %s\n" "$seq_num" "$severity" "$component" "$recommendation"
        seq_num=$((seq_num + 1))
    done < "${ALERT_LOG}"

    # Team notification mapping
    echo ""
    echo "  TEAM NOTIFICATION MAP:"
    echo "  ========================================================================================"
    local -A team_map
    while IFS='|' read -r severity component message recommendation; do
        case "$component" in
            ORACLE*) team_map["Oracle-DBA-Team"]=1 ;;
            S3FS*|CLOUD*) team_map["Cloud-AWS-Team"]=1 ;;
            NFS*) team_map["Network-Team"]=1; team_map["Storage-Team"]=1 ;;
            DISK*) team_map["Storage-VMware-Team"]=1 ;;
            SSH*|SUID*|BRUTE*|SELINUX*|FIREWALL*|CERT*|UID0*|EMPTY-PASSWORD*|WORLD-WRITABLE*|AUDIT*|CIS*|VAPT*|PWQUALITY*|PASSWORD*) team_map["Security-Team"]=1 ;;
            BACKUP*) team_map["Backup-Team"]=1 ;;
            PATCHING*|SECURITY-PATCHES*|SUBSCRIPTION*) team_map["Patch-Management-Team"]=1 ;;
            *) team_map["Application-Team"]=1; team_map["Unix-Admin-Team"]=1 ;;
        esac
    done < "${ALERT_LOG}"

    for team in "${!team_map[@]}"; do
        echo "  --> NOTIFY: ${team}"
    done
    echo ""
}

#=============================================================================
# HTML REPORT GENERATION
#=============================================================================
generate_html_report() {
    local txt_content="$1"

    cat > "${HTML_FILE}" <<'HTMLHEAD'
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Linux Health Check Report</title>
<style>
:root { --critical:#dc3545; --warning:#fd7e14; --ok:#28a745; --info:#17a2b8; --bg:#f4f6f9; --card:#fff; --text:#212529; --border:#dee2e6; --header:#0d1b3e; }
*{margin:0;padding:0;box-sizing:border-box}
body{font-family:'Segoe UI',Tahoma,sans-serif;background:var(--bg);color:var(--text);line-height:1.5}
.header{background:linear-gradient(135deg,#0d1b3e,#1a3a6c);color:#fff;padding:20px 40px;display:flex;justify-content:space-between;align-items:center}
.header h1{font-size:22px;font-weight:600}
.header .meta{font-size:12px;opacity:.85;text-align:right}
.status-bar{display:flex;gap:15px;padding:12px 40px;background:#fff;border-bottom:2px solid var(--border);flex-wrap:wrap;align-items:center}
.badge{padding:6px 16px;border-radius:6px;font-weight:700;font-size:13px;color:#fff}
.b-crit{background:var(--critical)}.b-warn{background:var(--warning)}.b-ok{background:var(--ok)}.b-info{background:var(--info)}
.container{max-width:1300px;margin:20px auto;padding:0 20px}
.section{background:var(--card);border-radius:8px;margin-bottom:16px;overflow:hidden;box-shadow:0 1px 4px rgba(0,0,0,.08)}
.sh{padding:12px 20px;font-size:15px;font-weight:600;cursor:pointer;display:flex;justify-content:space-between;align-items:center;transition:background .2s}
.sh-perf{background:#1565c0;color:#fff}.sh-perf:hover{background:#1976d2}
.sh-sec{background:#c62828;color:#fff}.sh-sec:hover{background:#d32f2f}
.sh-cis{background:#e65100;color:#fff}.sh-cis:hover{background:#ef6c00}
.sh-infra{background:#2e7d32;color:#fff}.sh-infra:hover{background:#388e3c}
.sh-alert{background:#b71c1c;color:#fff}.sh-alert:hover{background:#c62828}
.sh-patch{background:#4527a0;color:#fff}.sh-patch:hover{background:#5e35b1}
.sb{padding:15px 20px}
pre{background:#1e1e1e;color:#d4d4d4;padding:15px;border-radius:6px;overflow-x:auto;font-size:12.5px;line-height:1.5;white-space:pre-wrap;word-wrap:break-word;font-family:'Cascadia Code','Fira Code',Consolas,monospace}
.tbl{width:100%;border-collapse:collapse;margin:10px 0}
.tbl th{background:#37474f;color:#fff;padding:8px 12px;text-align:left;font-size:12px}
.tbl td{padding:8px 12px;border-bottom:1px solid var(--border);font-size:12px}
.tbl tr:hover{background:#f5f5f5}
.sev-CRITICAL{color:var(--critical);font-weight:700}.sev-WARNING{color:var(--warning);font-weight:700}.sev-INFO{color:var(--info);font-weight:700}
.rec{background:#fff3e0;border-left:4px solid var(--warning);padding:10px 12px;margin:4px 0;border-radius:0 4px 4px 0;font-size:12px}
.tag{display:inline-block;padding:4px 12px;margin:3px;border-radius:20px;font-size:11px;font-weight:600;color:#fff}
.tag-sec{background:#c62828}.tag-dba{background:#1565c0}.tag-app{background:#2e7d32}.tag-net{background:#e65100}.tag-unix{background:#37474f}.tag-patch{background:#4527a0}.tag-backup{background:#00838f}.tag-cloud{background:#6a1b9a}.tag-storage{background:#4e342e}
.footer{text-align:center;padding:20px;color:#888;font-size:11px;border-top:1px solid var(--border)}
.toggle{font-size:11px;background:rgba(255,255,255,.2);border:none;color:#fff;padding:2px 10px;border-radius:3px;cursor:pointer}
@media print{.sh{-webkit-print-color-adjust:exact;print-color-adjust:exact}.toggle{display:none}}
</style>
</head>
<body>
HTMLHEAD

    # Header
    cat >> "${HTML_FILE}" <<EOF
<div class="header">
  <div>
    <h1>${BANK_NAME} - Linux Health &amp; Security Report</h1>
    <div style="font-size:13px;margin-top:4px">Performance | Security | VAPT | CIS Compliance | v3.0</div>
  </div>
  <div class="meta">
    <div><strong>Host:</strong> ${HOSTNAME_S}</div>
    <div><strong>OS:</strong> ${OS_VERSION}</div>
    <div><strong>Kernel:</strong> ${KERNEL}</div>
    <div><strong>Date:</strong> ${TIME_STAMP}</div>
  </div>
</div>
EOF

    # Status bar
    local cc wc ic
    cc=$(grep -c "^CRITICAL" "${ALERT_LOG}" 2>/dev/null || echo 0)
    wc=$(grep -c "^WARNING" "${ALERT_LOG}" 2>/dev/null || echo 0)
    ic=$(grep -c "^INFO" "${ALERT_LOG}" 2>/dev/null || echo 0)

    echo '<div class="status-bar">' >> "${HTML_FILE}"
    (( cc > 0 )) && echo "<span class=\"badge b-crit\">CRITICAL: ${cc}</span>" >> "${HTML_FILE}"
    (( wc > 0 )) && echo "<span class=\"badge b-warn\">WARNING: ${wc}</span>" >> "${HTML_FILE}"
    (( ic > 0 )) && echo "<span class=\"badge b-info\">INFO: ${ic}</span>" >> "${HTML_FILE}"
    (( cc == 0 && wc == 0 )) && echo '<span class="badge b-ok">ALL HEALTHY</span>' >> "${HTML_FILE}"
    echo "<span style=\"padding:6px;font-size:12px;\">Uptime: ${UPTIME_STR} | CPUs: ${CPU_COUNT} | Reboot: ${LAST_REBOOT}</span>" >> "${HTML_FILE}"
    echo '</div><div class="container">' >> "${HTML_FILE}"

    # Alert summary at top
    if [[ -s "${ALERT_LOG}" ]]; then
        cat >> "${HTML_FILE}" <<'EOF'
<div class="section">
<div class="sh sh-alert">ALERT SUMMARY &amp; RECOMMENDATIONS <button class="toggle" onclick="let b=this.parentElement.nextElementSibling;b.style.display=b.style.display==='none'?'block':'none'">Toggle</button></div>
<div class="sb">
<table class="tbl"><tr><th>#</th><th>Severity</th><th>Component</th><th>Finding</th><th>Recommendation</th></tr>
EOF
        local seq=1
        while IFS='|' read -r sev comp msg rec; do
            msg=$(echo "$msg" | sed 's/&/\&amp;/g;s/</\&lt;/g;s/>/\&gt;/g')
            rec=$(echo "$rec" | sed 's/&/\&amp;/g;s/</\&lt;/g;s/>/\&gt;/g')
            echo "<tr><td>${seq}</td><td><span class=\"sev-${sev}\">${sev}</span></td><td>${comp}</td><td>${msg}</td><td><div class=\"rec\">${rec}</div></td></tr>" >> "${HTML_FILE}"
            seq=$((seq + 1))
        done < "${ALERT_LOG}"
        echo '</table>' >> "${HTML_FILE}"

        # Team tags
        echo '<div style="margin-top:12px"><strong>Teams to Notify:</strong><br>' >> "${HTML_FILE}"
        local -A html_teams
        while IFS='|' read -r sev comp msg rec; do
            case "$comp" in
                ORACLE*) html_teams["Oracle DBA"]="tag-dba" ;;
                S3FS*) html_teams["Cloud/AWS"]="tag-cloud" ;;
                NFS*) html_teams["Network"]="tag-net"; html_teams["Storage"]="tag-storage" ;;
                DISK*) html_teams["Storage/VMware"]="tag-storage" ;;
                SSH*|SUID*|BRUTE*|SELINUX*|FIREWALL*|CERT*|UID0*|EMPTY*|WORLD*|AUDIT*|CIS*|VAPT*|PW*|PASSWORD*) html_teams["Security"]="tag-sec" ;;
                BACKUP*) html_teams["Backup"]="tag-backup" ;;
                PATCHING*|SECURITY-PATCHES*|SUBSCRIPTION*) html_teams["Patch Mgmt"]="tag-patch" ;;
                *) html_teams["Application"]="tag-app"; html_teams["Unix Admin"]="tag-unix" ;;
            esac
        done < "${ALERT_LOG}"
        for team in "${!html_teams[@]}"; do
            echo "<span class=\"tag ${html_teams[$team]}\">${team}</span>" >> "${HTML_FILE}"
        done
        echo '</div></div></div>' >> "${HTML_FILE}"
    fi

    # Map sections to header classes
    declare -A section_class=(
        [1]="sh-perf" [2]="sh-perf" [3]="sh-perf" [4]="sh-perf" [5]="sh-perf"
        [6]="sh-perf" [7]="sh-perf" [8]="sh-perf" [9]="sh-perf"
        [10]="sh-sec" [11]="sh-cis" [12]="sh-infra" [13]="sh-patch" [14]="sh-alert"
    )
    declare -A section_names=(
        [1]="System Identity" [2]="CPU Statistics" [3]="Memory Statistics" [4]="Swap Utilization"
        [5]="Disk I/O & Latency" [6]="Filesystem Utilization" [7]="NFS Health"
        [8]="S3FS Mount Stats" [9]="Historical Analysis (SAR)"
        [10]="Security & VAPT Audit" [11]="CIS Benchmark Compliance"
        [12]="Infrastructure & Operational" [13]="Patching & Compliance"
    )

    for i in {1..13}; do
        local section_content
        section_content=$(echo "$txt_content" | sed -n "/^\[${i}\]/,/^\[$((i+1))\]/p" | head -n -1)
        [[ -z "$section_content" ]] && section_content=$(echo "$txt_content" | sed -n "/^\[${i}\]/,\$p")
        [[ -z "$section_content" ]] && continue

        section_content=$(echo "$section_content" | sed 's/&/\&amp;/g;s/</\&lt;/g;s/>/\&gt;/g')
        section_content=$(echo "$section_content" | \
            sed 's/\*\*\* ALERT \*\*\*/<span style="color:#dc3545;font-weight:bold">\&amp;\&amp;\&amp; ALERT \&amp;\&amp;\&amp;<\/span>/g' | \
            sed 's/BREACH:/<span style="color:#fd7e14;font-weight:bold">BREACH:<\/span>/g' | \
            sed 's/NON-COMPLIANT/<span style="color:#dc3545;font-weight:bold">NON-COMPLIANT<\/span>/g' | \
            sed 's/COMPLIANT/<span style="color:#28a745;font-weight:bold">COMPLIANT<\/span>/g' | \
            sed 's/RESPONSIVE/<span style="color:#28a745;font-weight:bold">RESPONSIVE<\/span>/g' | \
            sed 's/\*\*\* HUNG/<span style="color:#dc3545;font-weight:bold">\&amp;\&amp;\&amp; HUNG<\/span>/g' | \
            sed 's/\*\*\* SUSPICIOUS/<span style="color:#dc3545;font-weight:bold">\&amp;\&amp;\&amp; SUSPICIOUS<\/span>/g' | \
            sed 's/\*\*\* LOCKED/<span style="color:#fd7e14;font-weight:bold">\&amp;\&amp;\&amp; LOCKED<\/span>/g')

        local hdr_class="${section_class[$i]:-sh-perf}"
        local hdr_name="${section_names[$i]:-Section $i}"

        cat >> "${HTML_FILE}" <<EOF
<div class="section">
<div class="sh ${hdr_class}">${hdr_name} <button class="toggle" onclick="let b=this.parentElement.nextElementSibling;b.style.display=b.style.display==='none'?'block':'none'">Toggle</button></div>
<div class="sb"><pre>${section_content}</pre></div>
</div>
EOF
    done

    cat >> "${HTML_FILE}" <<EOF
</div>
<div class="footer">${REPORT_FOOTER} | Report: ${TIME_STAMP} | ${HOSTNAME_S}</div>
</body></html>
EOF
}

#=============================================================================
# EMAIL ALERTING
#=============================================================================
send_email_alert() {
    [[ "${ENABLE_EMAIL_ALERT}" != "yes" ]] && return
    [[ ! -s "${ALERT_LOG}" ]] && return
    if ! check_command mail && ! check_command mailx && ! check_command sendmail; then
        echo "WARNING: No mail command found. Email skipped." >&2
        return
    fi

    local cc wc
    cc=$(grep -c "^CRITICAL" "${ALERT_LOG}" 2>/dev/null || echo 0)
    wc=$(grep -c "^WARNING" "${ALERT_LOG}" 2>/dev/null || echo 0)

    local subject="${EMAIL_SUBJECT_PREFIX} ${HOSTNAME_S}: ${cc} CRITICAL, ${wc} WARNING - ${DATE_STAMP}"
    local body="Linux Health & Security Check Alert - ${HOSTNAME_S}\n"
    body+="Generated: ${TIME_STAMP}\nOS: ${OS_VERSION}\n"
    body+="============================================\n\n"

    while IFS='|' read -r sev comp msg rec; do
        body+="[${sev}] ${comp}: ${msg}\n  --> ${rec}\n\n"
    done < "${ALERT_LOG}"

    body+="\nFull reports: ${TXT_FILE} | ${HTML_FILE}\n"

    if check_command mailx; then
        echo -e "$body" | mailx -s "$subject" -a "${HTML_FILE}" "${EMAIL_RECIPIENTS}" 2>/dev/null
    elif check_command mail; then
        echo -e "$body" | mail -s "$subject" "${EMAIL_RECIPIENTS}" 2>/dev/null
    fi
}

#=============================================================================
# SALT EVENT PUBLISHING
#=============================================================================
send_salt_event() {
    [[ "${ENABLE_SALT_EVENT}" != "yes" ]] && return
    [[ ! -s "${ALERT_LOG}" ]] && return
    if ! check_command salt-call; then
        echo "WARNING: salt-call not found. Salt event skipped." >&2
        return
    fi

    local cc wc
    cc=$(grep -c "^CRITICAL" "${ALERT_LOG}" 2>/dev/null || echo 0)
    wc=$(grep -c "^WARNING" "${ALERT_LOG}" 2>/dev/null || echo 0)

    local alerts_json="["
    local first=1
    while IFS='|' read -r sev comp msg rec; do
        (( first )) || alerts_json+=","
        first=0
        msg=$(echo "$msg" | sed 's/"/\\"/g')
        rec=$(echo "$rec" | sed 's/"/\\"/g')
        alerts_json+="{\"severity\":\"${sev}\",\"component\":\"${comp}\",\"message\":\"${msg}\",\"recommendation\":\"${rec}\"}"
    done < "${ALERT_LOG}"
    alerts_json+="]"

    local payload="{\"hostname\":\"${HOSTNAME_S}\",\"timestamp\":\"${TIME_STAMP}\",\"critical\":${cc},\"warning\":${wc},\"alerts\":${alerts_json}}"

    salt-call event.send "${SALT_EVENT_TAG}" "${payload}" --local 2>/dev/null || \
    salt-call event.fire_master "${payload}" "${SALT_EVENT_TAG}" 2>/dev/null || \
    echo "WARNING: Failed to publish Salt event." >&2
}

#=============================================================================
# CLEANUP OLD REPORTS (30 day retention)
#=============================================================================
cleanup_old_reports() {
    find "${REPORT_DIR}" -name "*_health_*.txt" -mtime +30 -delete 2>/dev/null
    find "${REPORT_DIR}" -name "*_health_*.html" -mtime +30 -delete 2>/dev/null
    find "${REPORT_DIR}" -name ".alert_findings_*.tmp" -mtime +2 -delete 2>/dev/null
}

#=============================================================================
# MAIN EXECUTION
#=============================================================================
main() {
    echo "$(date): Starting Linux Health & Security Check v3.0 on ${HOSTNAME_S}" >&2

    {
        check_dependencies
        collect_system_info
        collect_cpu_stats
        collect_memory_stats
        collect_swap_stats
        collect_disk_io
        collect_filesystem_stats
        collect_nfs_health
        collect_s3fs_stats
        collect_historical_stats
        collect_security_vapt
        collect_cis_compliance
        collect_infra_checks
        collect_patching_status
        generate_recommendations
    } | tee "${TXT_FILE}"

    generate_html_report "$(cat "${TXT_FILE}")"
    send_email_alert
    send_salt_event
    cleanup_old_reports

    echo "" >&2
    echo "$(date): Health & Security Check Complete" >&2
    echo "  TXT Report : ${TXT_FILE}" >&2
    echo "  HTML Report: ${HTML_FILE}" >&2

    if grep -q "^CRITICAL" "${ALERT_LOG}" 2>/dev/null; then exit 2
    elif grep -q "^WARNING" "${ALERT_LOG}" 2>/dev/null; then exit 1
    fi
    exit 0
}

main "$@"
