#!/bin/bash
###############################################################################
# Linux Health Check Script - Banking Production Environment
# Compatible: Oracle Linux 8, 9, 10 (RHEL-compatible)
# Purpose:    Comprehensive daily health check with threshold alerting
# Output:     /root/Linux_health/<hostname>_health_YYYYMMDD.txt & .html
# Scheduling: Systemd Timer (cron-free, banking compliance)
# Author:     Infrastructure Automation Team
# Version:    2.0
###############################################################################

set -o pipefail

#=============================================================================
# CONFIGURABLE THRESHOLDS (per-metric, editable)
#=============================================================================
THRESH_CPU=85          # CPU utilization % threshold
THRESH_MEMORY=85       # Memory utilization % threshold
THRESH_SWAP=70         # Swap utilization % threshold (lower = early warning)
THRESH_DISK_UTIL=85    # Disk I/O utilization % threshold
THRESH_DISK_AWAIT=50   # Disk await (ms) threshold
THRESH_FS=85           # Filesystem usage % threshold
THRESH_NFS_RETRANS=5   # NFS retransmission % threshold
THRESH_LOAD_FACTOR=2   # Load avg threshold = factor x CPU_count

#=============================================================================
# ALERTING CONFIGURATION
#=============================================================================
ENABLE_EMAIL_ALERT="yes"               # yes/no
ENABLE_SALT_EVENT="yes"                # yes/no
EMAIL_RECIPIENTS="unix-team@bank.com,infra-alerts@bank.com"
EMAIL_SUBJECT_PREFIX="[LINUX-HEALTH]"
SALT_EVENT_TAG="infra/health/alert"

#=============================================================================
# BANK BRANDING (for HTML report)
#=============================================================================
BANK_NAME="Your Bank Name"
BANK_LOGO_PATH=""    # Optional: /path/to/logo.png (base64 embedded)
REPORT_FOOTER="Generated by Infrastructure Automation | Confidential"

#=============================================================================
# ORACLE DATABASE SPECIFIC PROCESSES TO MONITOR
#=============================================================================
ORACLE_PROCS="ora_pmon|ora_smon|ora_dbw|ora_lgwr|ora_ckpt|ora_arc|ora_mmon|tnslsnr|ocssd|crsd|evmd"

#=============================================================================
# INTERNAL VARIABLES - DO NOT EDIT BELOW
#=============================================================================
HOSTNAME_S=$(hostname -s)
DATE_STAMP=$(date +%Y%m%d)
TIME_STAMP=$(date '+%Y-%m-%d %H:%M:%S')
REPORT_DIR="/root/Linux_health"
TXT_FILE="${REPORT_DIR}/${HOSTNAME_S}_health_${DATE_STAMP}.txt"
HTML_FILE="${REPORT_DIR}/${HOSTNAME_S}_health_${DATE_STAMP}.html"
ALERT_LOG="${REPORT_DIR}/.alert_findings_${DATE_STAMP}.tmp"
CPU_COUNT=$(nproc 2>/dev/null || grep -c ^processor /proc/cpuinfo)
OS_VERSION=$(cat /etc/oracle-release 2>/dev/null || cat /etc/redhat-release 2>/dev/null || echo "Unknown")
KERNEL=$(uname -r)
UPTIME_STR=$(uptime -p 2>/dev/null || uptime)
LAST_REBOOT=$(who -b 2>/dev/null | awk '{print $3,$4}')
SAR_DIR="/var/log/sa"
YESTERDAY=$(date -d "yesterday" +%d)
TODAY=$(date +%d)

mkdir -p "${REPORT_DIR}"
> "${ALERT_LOG}"

#=============================================================================
# UTILITY FUNCTIONS
#=============================================================================

log_alert() {
    # $1=severity (CRITICAL/WARNING/INFO), $2=component, $3=message, $4=recommendation
    echo "${1}|${2}|${3}|${4}" >> "${ALERT_LOG}"
}

safe_cmd() {
    # Execute command with timeout and fallback
    timeout 10 bash -c "$1" 2>/dev/null || echo "$2"
}

check_command() {
    command -v "$1" &>/dev/null
}

pct_bar() {
    # $1=percentage (integer)
    local pct=${1%%.*}
    local filled=$((pct / 5))
    local empty=$((20 - filled))
    printf '[%s%s] %3d%%' "$(printf '#%.0s' $(seq 1 $filled 2>/dev/null))" \
           "$(printf '.%.0s' $(seq 1 $empty 2>/dev/null))" "$pct"
}

get_sar_file() {
    # $1=day number (e.g., 04)
    local day="$1"
    # OL8/9/10 sar files: /var/log/sa/sa<DD> (binary), /var/log/sa/sar<DD> (text)
    local sar_bin="${SAR_DIR}/sa${day}"
    if [[ -f "$sar_bin" ]]; then
        echo "$sar_bin"
    else
        echo ""
    fi
}

#=============================================================================
# SECTION 1: SYSTEM IDENTITY & UPTIME
#=============================================================================
collect_system_info() {
    cat <<EOF
================================================================================
  LINUX HEALTH CHECK REPORT
  Host: ${HOSTNAME_S} | Date: ${TIME_STAMP}
================================================================================

[1] SYSTEM IDENTITY
--------------------------------------------------------------------------------
  Hostname       : $(hostname -f 2>/dev/null || hostname)
  OS Release     : ${OS_VERSION}
  Kernel         : ${KERNEL}
  Architecture   : $(uname -m)
  CPU Count      : ${CPU_COUNT}
  Uptime         : ${UPTIME_STR}
  Last Reboot    : ${LAST_REBOOT}
  SELinux Status : $(getenforce 2>/dev/null || echo "N/A")
  Run Date       : ${TIME_STAMP}

EOF
}

#=============================================================================
# SECTION 2: CPU STATISTICS
#=============================================================================
collect_cpu_stats() {
    echo "[2] CPU STATISTICS"
    echo "--------------------------------------------------------------------------------"

    # Current CPU snapshot
    if check_command mpstat; then
        echo "  >> Current CPU Utilization (mpstat 1 3 average):"
        local mpstat_out
        mpstat_out=$(mpstat 1 3 2>/dev/null | tail -1)
        local idle=$(echo "$mpstat_out" | awk '{print $NF}')
        local usage
        usage=$(echo "100 - ${idle}" | bc 2>/dev/null || echo "N/A")
        echo "     Overall CPU Usage : ${usage}%"
        if [[ "$usage" != "N/A" ]] && (( $(echo "$usage > $THRESH_CPU" | bc -l 2>/dev/null || echo 0) )); then
            log_alert "CRITICAL" "CPU" "Current CPU usage at ${usage}% (threshold: ${THRESH_CPU}%)" \
                "Investigate top CPU consumers. Notify Application/Oracle team if DB processes are dominant."
        fi
        echo ""
        mpstat -P ALL 1 1 2>/dev/null | head -20
    else
        echo "  mpstat not available - using /proc/stat"
        top -bn1 | head -5
    fi

    # Load Average
    echo ""
    echo "  >> Load Average:"
    local load_1 load_5 load_15
    read load_1 load_5 load_15 _ < /proc/loadavg
    local load_thresh=$((CPU_COUNT * THRESH_LOAD_FACTOR))
    printf "     1-min: %-8s  5-min: %-8s  15-min: %-8s  (threshold: %d)\n" \
           "$load_1" "$load_5" "$load_15" "$load_thresh"
    if (( $(echo "$load_1 > $load_thresh" | bc -l 2>/dev/null || echo 0) )); then
        log_alert "WARNING" "CPU-LOAD" "Load average ${load_1} exceeds threshold ${load_thresh}" \
            "High load detected. Check for runaway processes or resource contention."
    fi

    # Top 5 CPU consumers
    echo ""
    echo "  >> Top 5 CPU Consuming Processes:"
    printf "     %-8s %-6s %-6s %-10s %s\n" "PID" "%CPU" "%MEM" "USER" "COMMAND"
    echo "     -------------------------------------------------------"
    ps aux --sort=-%cpu | head -6 | tail -5 | while read user pid cpu mem vsz rss tty stat start time cmd; do
        printf "     %-8s %-6s %-6s %-10s %s\n" "$pid" "$cpu" "$mem" "$user" "${cmd:0:50}"
    done

    # Oracle-specific CPU check
    echo ""
    echo "  >> Oracle Process CPU Usage:"
    local ora_cpu
    ora_cpu=$(ps aux | grep -E "${ORACLE_PROCS}" | grep -v grep)
    if [[ -n "$ora_cpu" ]]; then
        echo "$ora_cpu" | sort -k3 -rn | head -5 | while read user pid cpu mem vsz rss tty stat start time cmd; do
            printf "     %-8s %-6s %-6s %-10s %s\n" "$pid" "$cpu" "$mem" "$user" "${cmd:0:50}"
            if (( $(echo "$cpu > $THRESH_CPU" | bc -l 2>/dev/null || echo 0) )); then
                log_alert "CRITICAL" "ORACLE-CPU" "Oracle process ${cmd:0:30} (PID:${pid}) at ${cpu}% CPU" \
                    "Notify Oracle DBA team immediately. Check for long-running queries or rman jobs."
            fi
        done
    else
        echo "     No Oracle processes detected on this host."
    fi
    echo ""
}

#=============================================================================
# SECTION 3: MEMORY STATISTICS
#=============================================================================
collect_memory_stats() {
    echo "[3] MEMORY STATISTICS"
    echo "--------------------------------------------------------------------------------"

    local mem_total mem_used mem_free mem_available mem_buffers mem_cached mem_pct
    mem_total=$(grep MemTotal /proc/meminfo | awk '{print $2}')
    mem_free=$(grep MemFree /proc/meminfo | awk '{print $2}')
    mem_available=$(grep MemAvailable /proc/meminfo | awk '{print $2}')
    mem_buffers=$(grep Buffers /proc/meminfo | awk '{print $2}')
    mem_cached=$(grep "^Cached:" /proc/meminfo | awk '{print $2}')
    mem_used=$((mem_total - mem_free - mem_buffers - mem_cached))
    mem_pct=$((mem_used * 100 / mem_total))

    local total_gb=$(echo "scale=2; $mem_total/1048576" | bc)
    local used_gb=$(echo "scale=2; $mem_used/1048576" | bc)
    local free_gb=$(echo "scale=2; $mem_free/1048576" | bc)
    local avail_gb=$(echo "scale=2; $mem_available/1048576" | bc)
    local buf_gb=$(echo "scale=2; $mem_buffers/1048576" | bc)
    local cache_gb=$(echo "scale=2; $mem_cached/1048576" | bc)

    echo "  >> Physical Memory:"
    printf "     Total: %-10s  Used: %-10s  Free: %-10s\n" "${total_gb} GB" "${used_gb} GB" "${free_gb} GB"
    printf "     Available: %-10s  Buffers: %-10s  Cached: %-10s\n" "${avail_gb} GB" "${buf_gb} GB" "${cache_gb} GB"
    printf "     Utilization: %s\n" "$(pct_bar $mem_pct)"
    echo ""

    if (( mem_pct > THRESH_MEMORY )); then
        log_alert "CRITICAL" "MEMORY" "Memory utilization at ${mem_pct}% (threshold: ${THRESH_MEMORY}%)" \
            "Investigate high memory consumers. Notify Application team for potential memory leak or Oracle DBA for SGA/PGA tuning."
    fi

    # Huge Pages (important for Oracle)
    echo "  >> Huge Pages:"
    grep -i huge /proc/meminfo 2>/dev/null | while read line; do
        echo "     $line"
    done

    # Top 5 Memory consumers
    echo ""
    echo "  >> Top 5 Memory Consuming Processes:"
    printf "     %-8s %-6s %-12s %-10s %s\n" "PID" "%MEM" "RSS(MB)" "USER" "COMMAND"
    echo "     -------------------------------------------------------"
    ps aux --sort=-%mem | head -6 | tail -5 | while read user pid cpu mem vsz rss tty stat start time cmd; do
        local rss_mb=$((rss / 1024))
        printf "     %-8s %-6s %-12s %-10s %s\n" "$pid" "$mem" "$rss_mb" "$user" "${cmd:0:50}"
    done
    echo ""
}

#=============================================================================
# SECTION 4: SWAP UTILIZATION
#=============================================================================
collect_swap_stats() {
    echo "[4] SWAP UTILIZATION"
    echo "--------------------------------------------------------------------------------"

    local swap_total swap_used swap_free swap_pct
    swap_total=$(grep SwapTotal /proc/meminfo | awk '{print $2}')
    swap_used=$((swap_total - $(grep SwapFree /proc/meminfo | awk '{print $2}')))
    swap_free=$(grep SwapFree /proc/meminfo | awk '{print $2}')

    if (( swap_total > 0 )); then
        swap_pct=$((swap_used * 100 / swap_total))
    else
        swap_pct=0
    fi

    local stotal_gb=$(echo "scale=2; $swap_total/1048576" | bc)
    local sused_gb=$(echo "scale=2; $swap_used/1048576" | bc)
    local sfree_gb=$(echo "scale=2; $swap_free/1048576" | bc)

    printf "     Total: %-10s  Used: %-10s  Free: %-10s\n" "${stotal_gb} GB" "${sused_gb} GB" "${sfree_gb} GB"
    printf "     Utilization: %s\n" "$(pct_bar $swap_pct)"
    echo ""

    if (( swap_pct > THRESH_SWAP )); then
        log_alert "CRITICAL" "SWAP" "Swap usage at ${swap_pct}% (threshold: ${THRESH_SWAP}%)" \
            "High swap usage indicates memory pressure. Notify Application/Oracle team to review memory-hungry processes."
    fi

    # Top swap consuming processes
    echo "  >> Top 10 Processes Consuming Swap:"
    printf "     %-8s %-12s %-10s %s\n" "PID" "SWAP(MB)" "USER" "COMMAND"
    echo "     -------------------------------------------------------"
    local found_swap=0
    for pid_dir in /proc/[0-9]*; do
        local pid=$(basename "$pid_dir")
        if [[ -f "${pid_dir}/smaps_rollup" ]]; then
            local swap_kb=$(awk '/^Swap:/{sum+=$2}END{print sum}' "${pid_dir}/smaps_rollup" 2>/dev/null)
        elif [[ -f "${pid_dir}/smaps" ]]; then
            local swap_kb=$(awk '/^Swap:/{sum+=$2}END{print sum}' "${pid_dir}/smaps" 2>/dev/null)
        else
            continue
        fi
        if [[ -n "$swap_kb" ]] && (( swap_kb > 0 )); then
            local cmd_name=$(cat "${pid_dir}/comm" 2>/dev/null || echo "unknown")
            local proc_user=$(stat -c '%U' "${pid_dir}" 2>/dev/null || echo "unknown")
            echo "${swap_kb} ${pid} ${proc_user} ${cmd_name}"
            found_swap=1
        fi
    done 2>/dev/null | sort -rn | head -10 | while read swap_kb pid user cmd; do
        local swap_mb=$((swap_kb / 1024))
        printf "     %-8s %-12s %-10s %s\n" "$pid" "$swap_mb" "$user" "${cmd:0:50}"
        if echo "$cmd" | grep -qE "${ORACLE_PROCS}"; then
            log_alert "WARNING" "ORACLE-SWAP" "Oracle process ${cmd} (PID:${pid}) using ${swap_mb}MB swap" \
                "Notify Oracle DBA. Consider increasing physical memory or tuning SGA/PGA."
        fi
    done

    if (( found_swap == 0 )); then
        echo "     No significant swap usage detected."
    fi
    echo ""
}

#=============================================================================
# SECTION 5: DISK I/O & LATENCY
#=============================================================================
collect_disk_io() {
    echo "[5] DISK I/O & LATENCY"
    echo "--------------------------------------------------------------------------------"

    if check_command iostat; then
        echo "  >> Current I/O Statistics (iostat -xd 1 2):"
        echo ""
        printf "     %-12s %8s %8s %8s %8s %8s %8s %8s\n" \
               "DEVICE" "rrqm/s" "wrqm/s" "r/s" "w/s" "await" "svctm" "%util"
        echo "     ---------------------------------------------------------------------------"

        iostat -xd 1 2 2>/dev/null | awk '
        NR>1 && /^[a-z]/ && seen[$1]++ {
            printf "     %-12s %8s %8s %8s %8s %8s %8s %8s\n",
                   $1, $2, $3, $4, $5, $(NF-2), $(NF-1), $NF
        }' | while read line; do
            echo "$line"
            local dev=$(echo "$line" | awk '{print $1}')
            local util=$(echo "$line" | awk '{print $NF}')
            local await=$(echo "$line" | awk '{print $(NF-2)}')

            if (( $(echo "${util} > ${THRESH_DISK_UTIL}" | bc -l 2>/dev/null || echo 0) )); then
                log_alert "CRITICAL" "DISK-IO" "Device ${dev} I/O utilization at ${util}% (threshold: ${THRESH_DISK_UTIL}%)" \
                    "High disk I/O on ${dev}. Check for heavy write operations. Notify Oracle/Application team if DB datafiles reside here."
            fi
            if (( $(echo "${await} > ${THRESH_DISK_AWAIT}" | bc -l 2>/dev/null || echo 0) )); then
                log_alert "WARNING" "DISK-LATENCY" "Device ${dev} await at ${await}ms (threshold: ${THRESH_DISK_AWAIT}ms)" \
                    "High disk latency on ${dev}. Possible SAN/storage bottleneck. Engage Storage team."
            fi
        done
    else
        echo "  iostat not available. Install sysstat package."
    fi
    echo ""
}

#=============================================================================
# SECTION 6: FILESYSTEM UTILIZATION
#=============================================================================
collect_filesystem_stats() {
    echo "[6] FILESYSTEM UTILIZATION"
    echo "--------------------------------------------------------------------------------"

    echo "  >> Local & SAN Filesystems:"
    printf "     %-35s %8s %8s %8s %6s %s\n" "FILESYSTEM" "SIZE" "USED" "AVAIL" "USE%" "MOUNT"
    echo "     ---------------------------------------------------------------------------------"

    df -hP -x tmpfs -x devtmpfs -x nfs -x nfs4 -x s3fs 2>/dev/null | tail -n +2 | sort -k5 -rn | while read fs size used avail pct mount; do
        local pct_num=${pct%%%}
        local flag=""
        if (( pct_num >= THRESH_FS )); then
            flag=" *** ALERT ***"
            log_alert "CRITICAL" "FILESYSTEM" "Filesystem ${mount} (${fs}) at ${pct} (threshold: ${THRESH_FS}%)" \
                "Filesystem nearing capacity. Identify large files/logs. Notify Application team for cleanup or extend via LVM."
        fi
        printf "     %-35s %8s %8s %8s %6s %s%s\n" "$fs" "$size" "$used" "$avail" "$pct" "$mount" "$flag"
    done

    # Inode check
    echo ""
    echo "  >> Inode Utilization (>50% shown):"
    df -iP -x tmpfs -x devtmpfs -x nfs -x nfs4 2>/dev/null | tail -n +2 | while read fs total used free pct mount; do
        local pct_num=${pct%%%}
        if (( pct_num > 50 )); then
            printf "     %-35s %6s %s\n" "$fs" "$pct" "$mount"
            if (( pct_num >= THRESH_FS )); then
                log_alert "WARNING" "INODE" "Inode usage on ${mount} at ${pct}" \
                    "High inode usage may block file creation. Identify dirs with excessive small files."
            fi
        fi
    done
    echo ""
}

#=============================================================================
# SECTION 7: NFS HEALTH
#=============================================================================
collect_nfs_health() {
    echo "[7] NFS HEALTH"
    echo "--------------------------------------------------------------------------------"

    # Check NFS mounts
    local nfs_mounts
    nfs_mounts=$(mount -t nfs,nfs4 2>/dev/null)
    if [[ -z "$nfs_mounts" ]]; then
        echo "     No NFS mounts detected on this host."
        echo ""
        return
    fi

    echo "  >> NFS Mount Points:"
    printf "     %-40s %-20s %-8s %s\n" "SOURCE" "MOUNT" "TYPE" "OPTIONS"
    echo "     ---------------------------------------------------------------------------------"
    mount -t nfs,nfs4 2>/dev/null | while read src on mnt type fstype opts; do
        printf "     %-40s %-20s %-8s %s\n" "$src" "$mnt" "$fstype" "${opts:0:40}"
    done

    # NFS mount responsiveness check
    echo ""
    echo "  >> NFS Mount Responsiveness (5s timeout):"
    mount -t nfs,nfs4 2>/dev/null | awk '{print $3}' | while read mnt; do
        local start_ts=$(date +%s%N)
        if timeout 5 stat "$mnt" &>/dev/null; then
            local end_ts=$(date +%s%N)
            local latency_ms=$(( (end_ts - start_ts) / 1000000 ))
            printf "     %-30s : RESPONSIVE (%dms)\n" "$mnt" "$latency_ms"
            if (( latency_ms > 3000 )); then
                log_alert "WARNING" "NFS-SLOW" "NFS mount ${mnt} responding slowly (${latency_ms}ms)" \
                    "Possible network/NAS performance issue. Engage Network/Storage team."
            fi
        else
            printf "     %-30s : *** HUNG/TIMEOUT ***\n" "$mnt"
            log_alert "CRITICAL" "NFS-HUNG" "NFS mount ${mnt} is HUNG or not responding" \
                "IMMEDIATE ACTION: NFS mount hung. Check NFS server, network. May need umount -f. Engage Storage/Network team."
        fi
    done

    # NFS filesystem stats
    echo ""
    echo "  >> NFS Filesystem Utilization:"
    df -hP -t nfs -t nfs4 2>/dev/null | tail -n +2 | while read fs size used avail pct mount; do
        local pct_num=${pct%%%}
        local flag=""
        if (( pct_num >= THRESH_FS )); then
            flag=" *** ALERT ***"
            log_alert "WARNING" "NFS-SPACE" "NFS mount ${mount} at ${pct}" \
                "NFS share nearing capacity. Coordinate with NFS server admin for cleanup or expansion."
        fi
        printf "     %-35s %8s %8s %8s %6s %s%s\n" "$fs" "$size" "$used" "$avail" "$pct" "$mount" "$flag"
    done

    # NFS RPC statistics
    if check_command nfsstat; then
        echo ""
        echo "  >> NFS RPC Statistics (summary):"
        nfsstat -c 2>/dev/null | head -15 | sed 's/^/     /'
    fi

    # NFS I/O stats
    if check_command nfsiostat; then
        echo ""
        echo "  >> NFS I/O Statistics:"
        nfsiostat 2>/dev/null | head -30 | sed 's/^/     /'
    fi

    # Check for stale handles
    echo ""
    echo "  >> Stale NFS Handle Check:"
    local stale_count=$(dmesg 2>/dev/null | grep -ci "stale.*nfs\|nfs.*stale" || echo 0)
    if (( stale_count > 0 )); then
        echo "     *** ${stale_count} stale NFS handle message(s) found in dmesg ***"
        log_alert "WARNING" "NFS-STALE" "${stale_count} stale NFS handle errors in dmesg" \
            "Stale NFS handles detected. Files may have been deleted on server. Remount may be required."
    else
        echo "     No stale NFS handle errors found."
    fi
    echo ""
}

#=============================================================================
# SECTION 8: S3FS MOUNT STATS
#=============================================================================
collect_s3fs_stats() {
    echo "[8] S3FS MOUNT STATISTICS"
    echo "--------------------------------------------------------------------------------"

    local s3fs_mounts
    s3fs_mounts=$(mount -t fuse.s3fs 2>/dev/null || grep s3fs /proc/mounts 2>/dev/null)

    if [[ -z "$s3fs_mounts" ]]; then
        echo "     No S3FS mounts detected on this host."
        echo ""
        return
    fi

    echo "  >> S3FS Mount Points:"
    echo "$s3fs_mounts" | while read src mnt fstype opts rest; do
        printf "     Source: %-30s  Mount: %-20s  Type: %s\n" "$src" "$mnt" "$fstype"

        # Responsiveness
        if timeout 10 stat "$mnt" &>/dev/null; then
            echo "     Status: RESPONSIVE"
            df -hP "$mnt" 2>/dev/null | tail -1 | while read fs size used avail pct mount; do
                printf "     Size: %-8s  Used: %-8s  Available: %-8s  Usage: %s\n" "$size" "$used" "$avail" "$pct"
            done
        else
            echo "     Status: *** NOT RESPONDING (10s timeout) ***"
            log_alert "CRITICAL" "S3FS" "S3FS mount ${mnt} not responding" \
                "S3FS mount failure. Check AWS credentials, network connectivity, and s3fs process. Engage Cloud team."
        fi
        echo ""
    done
    echo ""
}

#=============================================================================
# SECTION 9: SAR / VMSTAT / MPSTAT / IOSTAT HISTORICAL (LAST 24 HOURS)
#=============================================================================
collect_historical_stats() {
    echo "[9] HISTORICAL ANALYSIS - LAST 24 HOURS (SAR/VMSTAT/MPSTAT/IOSTAT)"
    echo "================================================================================"

    local sar_yesterday sar_today
    sar_yesterday=$(get_sar_file "$YESTERDAY")
    sar_today=$(get_sar_file "$TODAY")

    if [[ -z "$sar_yesterday" && -z "$sar_today" ]]; then
        echo "  *** SAR data not available. Ensure sysstat is installed and sa1/sa2 are running. ***"
        log_alert "WARNING" "SAR-DATA" "SAR data files not found in ${SAR_DIR}" \
            "Install/enable sysstat for historical monitoring: yum install sysstat && systemctl enable --now sysstat"
        echo ""
        return
    fi

    # ---- 9a: CPU Historical ----
    echo ""
    echo "  [9a] CPU Usage History (sar -u)"
    echo "  -----------------------------------------------"
    echo "  Peak values and threshold breaches:"
    echo ""

    local cpu_breach_count=0
    for sar_file in "$sar_yesterday" "$sar_today"; do
        [[ -z "$sar_file" || ! -f "$sar_file" ]] && continue
        local day_label
        if [[ "$sar_file" == *"sa${YESTERDAY}" ]]; then day_label="YESTERDAY"; else day_label="TODAY"; fi

        echo "  -- ${day_label} --"
        local peak_cpu peak_time
        peak_line=$(sar -u -f "$sar_file" 2>/dev/null | grep -v "^$\|Linux\|Average\|%idle\|RESTART" | \
                    awk '{idle=$NF; cpu=100-idle; if(cpu>max){max=cpu; line=$0}} END{print max"|"line}')
        peak_cpu=$(echo "$peak_line" | cut -d'|' -f1)

        if [[ -n "$peak_cpu" ]] && [[ "$peak_cpu" != "0" ]]; then
            printf "     Peak CPU: %.1f%%\n" "$peak_cpu"

            # Find all breaches
            sar -u -f "$sar_file" 2>/dev/null | grep -v "^$\|Linux\|Average\|%idle\|RESTART" | \
            awk -v thresh="$THRESH_CPU" '{
                idle=$NF; cpu=100-idle;
                if(cpu>thresh) {
                    printf "     BREACH: %s - CPU %.1f%% (idle: %s)\n", $1, cpu, $NF
                    count++
                }
            } END { if(count>0) printf "     Total breaches: %d intervals\n", count }'

            if (( $(echo "$peak_cpu > $THRESH_CPU" | bc -l 2>/dev/null || echo 0) )); then
                cpu_breach_count=$((cpu_breach_count + 1))
            fi
        else
            echo "     No data available."
        fi
        echo ""
    done

    if (( cpu_breach_count > 0 )); then
        log_alert "CRITICAL" "SAR-CPU" "CPU exceeded ${THRESH_CPU}% threshold in last 24h" \
            "Historical CPU spikes detected. Correlate timestamps with application batch jobs or Oracle operations."
    fi

    # ---- 9b: Memory Historical ----
    echo "  [9b] Memory Usage History (sar -r)"
    echo "  -----------------------------------------------"
    for sar_file in "$sar_yesterday" "$sar_today"; do
        [[ -z "$sar_file" || ! -f "$sar_file" ]] && continue
        local day_label
        if [[ "$sar_file" == *"sa${YESTERDAY}" ]]; then day_label="YESTERDAY"; else day_label="TODAY"; fi

        echo "  -- ${day_label} --"
        sar -r -f "$sar_file" 2>/dev/null | grep -v "^$\|Linux\|RESTART" | \
        awk -v thresh="$THRESH_MEMORY" '
        /Average/ { printf "     Average: MemUsed%%: %s  Committed%%: N/A\n", $5; next }
        /^[0-9]/ {
            if($5+0 > thresh) {
                printf "     BREACH: %s - MemUsed: %s%%\n", $1, $5
                count++
            }
            if($5+0 > max) { max=$5+0 }
        }
        END {
            printf "     Peak MemUsed%%: %.1f%%\n", max
            if(count>0) printf "     Total breaches: %d intervals\n", count
        }'
        echo ""
    done

    # ---- 9c: Swap Historical ----
    echo "  [9c] Swap Usage History (sar -S)"
    echo "  -----------------------------------------------"
    for sar_file in "$sar_yesterday" "$sar_today"; do
        [[ -z "$sar_file" || ! -f "$sar_file" ]] && continue
        local day_label
        if [[ "$sar_file" == *"sa${YESTERDAY}" ]]; then day_label="YESTERDAY"; else day_label="TODAY"; fi

        echo "  -- ${day_label} --"
        sar -S -f "$sar_file" 2>/dev/null | grep -v "^$\|Linux\|RESTART" | \
        awk -v thresh="$THRESH_SWAP" '
        /Average/ { printf "     Average SwapUsed%%: %s\n", $5; next }
        /^[0-9]/ {
            if($5+0 > thresh) {
                printf "     BREACH: %s - SwapUsed: %s%%\n", $1, $5
                count++
            }
            if($5+0 > max) { max=$5+0 }
        }
        END {
            printf "     Peak SwapUsed%%: %.1f%%\n", max
            if(count>0) printf "     Total breaches: %d intervals\n", count
        }'
        echo ""
    done

    # ---- 9d: Disk I/O Historical ----
    echo "  [9d] Disk I/O History (sar -d)"
    echo "  -----------------------------------------------"
    for sar_file in "$sar_yesterday" "$sar_today"; do
        [[ -z "$sar_file" || ! -f "$sar_file" ]] && continue
        local day_label
        if [[ "$sar_file" == *"sa${YESTERDAY}" ]]; then day_label="YESTERDAY"; else day_label="TODAY"; fi

        echo "  -- ${day_label} --"
        sar -d -f "$sar_file" 2>/dev/null | grep -v "^$\|Linux\|RESTART" | \
        awk -v util_thresh="$THRESH_DISK_UTIL" -v await_thresh="$THRESH_DISK_AWAIT" '
        /Average/ {
            printf "     Avg Device: %-12s  await: %s ms  %%util: %s%%\n", $2, $(NF-1), $NF
            next
        }
        /^[0-9]/ {
            if($NF+0 > util_thresh) {
                printf "     BREACH [UTIL]: %s Dev:%-12s await:%s %%util:%s\n", $1, $2, $(NF-1), $NF
                ucount++
            }
            if($(NF-1)+0 > await_thresh) {
                printf "     BREACH [AWAIT]: %s Dev:%-12s await:%s ms\n", $1, $2, $(NF-1)
                acount++
            }
        }
        END {
            if(ucount>0) printf "     Utilization breaches: %d intervals\n", ucount
            if(acount>0) printf "     Await breaches: %d intervals\n", acount
        }'
        echo ""
    done

    # ---- 9e: Network Historical (bonus) ----
    echo "  [9e] Network Error History (sar -n EDEV) - Summary"
    echo "  -----------------------------------------------"
    for sar_file in "$sar_yesterday" "$sar_today"; do
        [[ -z "$sar_file" || ! -f "$sar_file" ]] && continue
        local day_label
        if [[ "$sar_file" == *"sa${YESTERDAY}" ]]; then day_label="YESTERDAY"; else day_label="TODAY"; fi

        echo "  -- ${day_label} --"
        sar -n EDEV -f "$sar_file" 2>/dev/null | grep "Average" | \
        awk '{
            if($3+0>0 || $4+0>0 || $5+0>0 || $6+0>0) {
                printf "     %-12s rxerr/s:%-6s txerr/s:%-6s coll/s:%-6s drop/s:%-6s\n",
                       $2, $3, $4, $5, $6
            }
        }'
        echo ""
    done

    # ---- 9f: Consolidated SAR Summary ----
    echo "  [9f] CONSOLIDATED 24-HOUR SUMMARY"
    echo "  ============================================================"
    echo ""
    printf "  %-20s %-15s %-15s %-10s\n" "METRIC" "PEAK VALUE" "THRESHOLD" "STATUS"
    echo "  ---------------------------------------------------------------"

    # Summarize from latest sar file
    local summary_file="${sar_today:-$sar_yesterday}"
    if [[ -n "$summary_file" && -f "$summary_file" ]]; then
        # CPU
        local peak_cpu_val=$(sar -u -f "$summary_file" 2>/dev/null | grep -v "^$\|Linux\|Average\|RESTART" | \
            awk '{cpu=100-$NF; if(cpu>max) max=cpu} END{printf "%.1f", max}')
        local cpu_status="OK"
        (( $(echo "$peak_cpu_val > $THRESH_CPU" | bc -l 2>/dev/null || echo 0) )) && cpu_status="BREACH"
        printf "  %-20s %-15s %-15s %-10s\n" "CPU Usage %" "${peak_cpu_val}%" "${THRESH_CPU}%" "$cpu_status"

        # Memory
        local peak_mem_val=$(sar -r -f "$summary_file" 2>/dev/null | grep -v "^$\|Linux\|Average\|RESTART" | \
            awk '/^[0-9]/{if($5+0>max) max=$5+0} END{printf "%.1f", max}')
        local mem_status="OK"
        (( $(echo "$peak_mem_val > $THRESH_MEMORY" | bc -l 2>/dev/null || echo 0) )) && mem_status="BREACH"
        printf "  %-20s %-15s %-15s %-10s\n" "Memory Usage %" "${peak_mem_val}%" "${THRESH_MEMORY}%" "$mem_status"

        # Swap
        local peak_swap_val=$(sar -S -f "$summary_file" 2>/dev/null | grep -v "^$\|Linux\|Average\|RESTART" | \
            awk '/^[0-9]/{if($5+0>max) max=$5+0} END{printf "%.1f", max}')
        local swap_status="OK"
        (( $(echo "$peak_swap_val > $THRESH_SWAP" | bc -l 2>/dev/null || echo 0) )) && swap_status="BREACH"
        printf "  %-20s %-15s %-15s %-10s\n" "Swap Usage %" "${peak_swap_val}%" "${THRESH_SWAP}%" "$swap_status"
    fi
    echo ""
}

#=============================================================================
# SECTION 10: ALERT SUMMARY & RECOMMENDATIONS
#=============================================================================
generate_recommendations() {
    echo "[10] ALERT SUMMARY & RECOMMENDATIONS"
    echo "================================================================================"
    echo ""

    if [[ ! -s "${ALERT_LOG}" ]]; then
        echo "  *** NO THRESHOLD BREACHES DETECTED - ALL SYSTEMS HEALTHY ***"
        echo ""
        return
    fi

    local critical_count warning_count
    critical_count=$(grep -c "^CRITICAL" "${ALERT_LOG}" 2>/dev/null || echo 0)
    warning_count=$(grep -c "^WARNING" "${ALERT_LOG}" 2>/dev/null || echo 0)

    echo "  Overall Status: ${critical_count} CRITICAL | ${warning_count} WARNING"
    echo ""

    local seq_num=1
    printf "  %-4s %-10s %-15s %-50s\n" "#" "SEVERITY" "COMPONENT" "FINDING"
    echo "  ---------------------------------------------------------------------------------"

    while IFS='|' read -r severity component message recommendation; do
        printf "  %-4s %-10s %-15s %s\n" "$seq_num" "$severity" "$component" "$message"
        seq_num=$((seq_num + 1))
    done < "${ALERT_LOG}"

    echo ""
    echo "  RECOMMENDATIONS:"
    echo "  ---------------------------------------------------------------------------------"
    seq_num=1
    while IFS='|' read -r severity component message recommendation; do
        printf "  %d. [%s] %s\n" "$seq_num" "$component" "$recommendation"
        seq_num=$((seq_num + 1))
    done < "${ALERT_LOG}"

    # Team notification mapping
    echo ""
    echo "  TEAM NOTIFICATION MAPPING:"
    echo "  ---------------------------------------------------------------------------------"
    local notify_oracle=0 notify_app=0 notify_storage=0 notify_network=0 notify_unix=0 notify_cloud=0

    while IFS='|' read -r severity component message recommendation; do
        case "$component" in
            ORACLE*) notify_oracle=1 ;;
            S3FS*) notify_cloud=1 ;;
            NFS*) notify_network=1; notify_storage=1 ;;
            DISK*) notify_storage=1 ;;
            *) notify_app=1; notify_unix=1 ;;
        esac
    done < "${ALERT_LOG}"

    (( notify_oracle )) && echo "  --> NOTIFY: Oracle DBA Team"
    (( notify_app ))    && echo "  --> NOTIFY: Application Team"
    (( notify_storage ))&& echo "  --> NOTIFY: Storage/SAN Team"
    (( notify_network ))&& echo "  --> NOTIFY: Network Team"
    (( notify_cloud ))  && echo "  --> NOTIFY: Cloud/AWS Team"
    (( notify_unix ))   && echo "  --> NOTIFY: Unix/Linux Admin Team"
    echo ""
}

#=============================================================================
# HTML REPORT GENERATION
#=============================================================================
generate_html_report() {
    local txt_content="$1"

    cat > "${HTML_FILE}" <<'HTMLHEAD'
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Linux Health Check Report</title>
<style>
:root {
    --critical: #dc3545;
    --warning: #fd7e14;
    --ok: #28a745;
    --info: #17a2b8;
    --bg: #f8f9fa;
    --card-bg: #ffffff;
    --text: #212529;
    --border: #dee2e6;
    --header-bg: #1a237e;
}
* { margin: 0; padding: 0; box-sizing: border-box; }
body {
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    background: var(--bg); color: var(--text); line-height: 1.6;
}
.header {
    background: var(--header-bg);
    color: #fff; padding: 20px 40px;
    display: flex; justify-content: space-between; align-items: center;
}
.header h1 { font-size: 24px; font-weight: 600; }
.header .meta { font-size: 13px; opacity: 0.85; text-align: right; }
.status-bar {
    display: flex; gap: 20px; padding: 15px 40px;
    background: #fff; border-bottom: 2px solid var(--border);
    flex-wrap: wrap;
}
.status-badge {
    padding: 8px 20px; border-radius: 6px; font-weight: 600;
    font-size: 14px; color: #fff;
}
.badge-critical { background: var(--critical); }
.badge-warning { background: var(--warning); }
.badge-ok { background: var(--ok); }
.container { max-width: 1200px; margin: 20px auto; padding: 0 20px; }
.section {
    background: var(--card-bg); border-radius: 8px;
    margin-bottom: 20px; overflow: hidden;
    box-shadow: 0 1px 3px rgba(0,0,0,0.1);
}
.section-header {
    background: #37474f; color: #fff;
    padding: 12px 20px; font-size: 16px; font-weight: 600;
    cursor: pointer;
}
.section-header:hover { background: #455a64; }
.section-body { padding: 20px; }
pre {
    background: #263238; color: #aed581;
    padding: 15px; border-radius: 4px;
    overflow-x: auto; font-size: 13px;
    line-height: 1.5; white-space: pre-wrap;
    word-wrap: break-word;
}
.alert-table { width: 100%; border-collapse: collapse; margin: 10px 0; }
.alert-table th {
    background: #37474f; color: #fff;
    padding: 10px 15px; text-align: left; font-size: 13px;
}
.alert-table td { padding: 10px 15px; border-bottom: 1px solid var(--border); font-size: 13px; }
.alert-table tr:hover { background: #f5f5f5; }
.severity-CRITICAL { color: var(--critical); font-weight: 700; }
.severity-WARNING { color: var(--warning); font-weight: 700; }
.severity-INFO { color: var(--info); font-weight: 700; }
.rec-box {
    background: #fff3e0; border-left: 4px solid var(--warning);
    padding: 12px 15px; margin: 8px 0; border-radius: 0 4px 4px 0;
    font-size: 13px;
}
.notify-tag {
    display: inline-block; padding: 4px 12px; margin: 4px;
    border-radius: 20px; font-size: 12px; font-weight: 600;
    background: var(--critical); color: #fff;
}
.footer {
    text-align: center; padding: 20px;
    color: #666; font-size: 12px; border-top: 1px solid var(--border);
}
.toggle-btn {
    float: right; font-size: 12px;
    background: rgba(255,255,255,0.2); border: none; color: #fff;
    padding: 3px 10px; border-radius: 3px; cursor: pointer;
}
@media print {
    .section-header { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
    .toggle-btn { display: none; }
}
</style>
</head>
<body>
HTMLHEAD

    # Header with bank branding
    cat >> "${HTML_FILE}" <<EOF
<div class="header">
    <div>
        <h1>${BANK_NAME} - Linux Health Check Report</h1>
        <div style="font-size:14px; margin-top:5px;">Infrastructure Monitoring | Compliance Report</div>
    </div>
    <div class="meta">
        <div><strong>Host:</strong> ${HOSTNAME_S}</div>
        <div><strong>OS:</strong> ${OS_VERSION}</div>
        <div><strong>Date:</strong> ${TIME_STAMP}</div>
        <div><strong>Kernel:</strong> ${KERNEL}</div>
    </div>
</div>
EOF

    # Status bar
    local critical_count warning_count
    critical_count=$(grep -c "^CRITICAL" "${ALERT_LOG}" 2>/dev/null || echo 0)
    warning_count=$(grep -c "^WARNING" "${ALERT_LOG}" 2>/dev/null || echo 0)

    echo '<div class="status-bar">' >> "${HTML_FILE}"
    if (( critical_count > 0 )); then
        echo "<span class=\"status-badge badge-critical\">CRITICAL: ${critical_count}</span>" >> "${HTML_FILE}"
    fi
    if (( warning_count > 0 )); then
        echo "<span class=\"status-badge badge-warning\">WARNING: ${warning_count}</span>" >> "${HTML_FILE}"
    fi
    if (( critical_count == 0 && warning_count == 0 )); then
        echo '<span class="status-badge badge-ok">ALL SYSTEMS HEALTHY</span>' >> "${HTML_FILE}"
    fi
    echo "<span style=\"padding:8px;font-size:13px;\">Uptime: ${UPTIME_STR} | CPUs: ${CPU_COUNT} | Last Reboot: ${LAST_REBOOT}</span>" >> "${HTML_FILE}"
    echo '</div>' >> "${HTML_FILE}"

    echo '<div class="container">' >> "${HTML_FILE}"

    # Alert summary section (if alerts exist)
    if [[ -s "${ALERT_LOG}" ]]; then
        cat >> "${HTML_FILE}" <<'EOF'
<div class="section">
    <div class="section-header">ALERT SUMMARY & RECOMMENDATIONS <button class="toggle-btn" onclick="this.parentElement.nextElementSibling.style.display=this.parentElement.nextElementSibling.style.display==='none'?'block':'none'">Toggle</button></div>
    <div class="section-body">
        <table class="alert-table">
            <tr><th>#</th><th>Severity</th><th>Component</th><th>Finding</th><th>Recommendation</th></tr>
EOF
        local seq=1
        while IFS='|' read -r severity component message recommendation; do
            cat >> "${HTML_FILE}" <<EOF
            <tr>
                <td>${seq}</td>
                <td><span class="severity-${severity}">${severity}</span></td>
                <td>${component}</td>
                <td>${message}</td>
                <td><div class="rec-box">${recommendation}</div></td>
            </tr>
EOF
            seq=$((seq + 1))
        done < "${ALERT_LOG}"

        echo '</table>' >> "${HTML_FILE}"

        # Team notifications
        echo '<div style="margin-top:15px;"><strong>Teams to Notify:</strong><br>' >> "${HTML_FILE}"
        local teams_notified=""
        while IFS='|' read -r severity component message recommendation; do
            case "$component" in
                ORACLE*) teams_notified="${teams_notified} Oracle-DBA" ;;
                S3FS*) teams_notified="${teams_notified} Cloud-Team" ;;
                NFS*) teams_notified="${teams_notified} Network-Team Storage-Team" ;;
                DISK*) teams_notified="${teams_notified} Storage-Team" ;;
                *) teams_notified="${teams_notified} Application-Team Unix-Admin" ;;
            esac
        done < "${ALERT_LOG}"

        for team in $(echo "$teams_notified" | tr ' ' '\n' | sort -u); do
            [[ -n "$team" ]] && echo "<span class=\"notify-tag\">${team}</span>" >> "${HTML_FILE}"
        done
        echo '</div></div></div>' >> "${HTML_FILE}"
    fi

    # Sections from text report
    local section_names=("System Identity" "CPU Statistics" "Memory Statistics" "Swap Utilization"
                         "Disk I/O & Latency" "Filesystem Utilization" "NFS Health"
                         "S3FS Mount Statistics" "Historical Analysis" "Alert Summary")

    for i in {1..9}; do
        local section_content
        section_content=$(echo "$txt_content" | sed -n "/^\[${i}\]/,/^\[$((i+1))\]/p" | head -n -1)
        if [[ -z "$section_content" ]]; then
            section_content=$(echo "$txt_content" | sed -n "/^\[${i}\]/,\$p")
        fi

        if [[ -n "$section_content" ]]; then
            # Escape HTML
            section_content=$(echo "$section_content" | sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g')

            # Color-code alerts in the pre block
            section_content=$(echo "$section_content" | \
                sed 's/\*\*\* ALERT \*\*\*/<span style="color:#dc3545;font-weight:bold">\*\*\* ALERT \*\*\*<\/span>/g' | \
                sed 's/BREACH:/<span style="color:#fd7e14;font-weight:bold">BREACH:<\/span>/g' | \
                sed 's/\*\*\* HUNG/<span style="color:#dc3545;font-weight:bold">\*\*\* HUNG<\/span>/g' | \
                sed 's/RESPONSIVE/<span style="color:#28a745;font-weight:bold">RESPONSIVE<\/span>/g')

            cat >> "${HTML_FILE}" <<EOF
<div class="section">
    <div class="section-header">${section_names[$((i-1))]:-Section $i} <button class="toggle-btn" onclick="this.parentElement.nextElementSibling.style.display=this.parentElement.nextElementSibling.style.display==='none'?'block':'none'">Toggle</button></div>
    <div class="section-body"><pre>${section_content}</pre></div>
</div>
EOF
        fi
    done

    # Footer
    cat >> "${HTML_FILE}" <<EOF
</div>
<div class="footer">
    ${REPORT_FOOTER} | Report generated: ${TIME_STAMP}
</div>
<script>
// Auto-collapse sections on load (except alerts)
document.querySelectorAll('.section-body').forEach((el, idx) => { if(idx > 0) { /* keep first open */ } });
</script>
</body>
</html>
EOF
}

#=============================================================================
# EMAIL ALERTING
#=============================================================================
send_email_alert() {
    if [[ "${ENABLE_EMAIL_ALERT}" != "yes" ]]; then return; fi
    if [[ ! -s "${ALERT_LOG}" ]]; then return; fi
    if ! check_command mail && ! check_command mailx && ! check_command sendmail; then
        echo "WARNING: No mail command available. Email alert skipped." >&2
        return
    fi

    local critical_count warning_count
    critical_count=$(grep -c "^CRITICAL" "${ALERT_LOG}" 2>/dev/null || echo 0)
    warning_count=$(grep -c "^WARNING" "${ALERT_LOG}" 2>/dev/null || echo 0)

    local subject="${EMAIL_SUBJECT_PREFIX} ${HOSTNAME_S}: ${critical_count} CRITICAL, ${warning_count} WARNING - ${DATE_STAMP}"
    local body=""
    body+="Linux Health Check Alert - ${HOSTNAME_S}
"
    body+="Generated: ${TIME_STAMP}
"
    body+="OS: ${OS_VERSION}
"
    body+="============================================
"
    body+=""

    while IFS='|' read -r severity component message recommendation; do
        body+="[${severity}] ${component}: ${message}
"
        body+="  --> ${recommendation}
"
        body+=""
    done < "${ALERT_LOG}"

    body+="
Full reports: ${TXT_FILE} | ${HTML_FILE}
"

    # Try sending email
    if check_command mailx; then
        echo "$body" | mailx -s "$subject" -a "${HTML_FILE}" "${EMAIL_RECIPIENTS}" 2>/dev/null
    elif check_command mail; then
        echo "$body" | mail -s "$subject" "${EMAIL_RECIPIENTS}" 2>/dev/null
    fi
}

#=============================================================================
# SALT EVENT PUBLISHING
#=============================================================================
send_salt_event() {
    if [[ "${ENABLE_SALT_EVENT}" != "yes" ]]; then return; fi
    if [[ ! -s "${ALERT_LOG}" ]]; then return; fi
    if ! check_command salt-call; then
        echo "WARNING: salt-call not available. Salt event skipped." >&2
        return
    fi

    local critical_count warning_count
    critical_count=$(grep -c "^CRITICAL" "${ALERT_LOG}" 2>/dev/null || echo 0)
    warning_count=$(grep -c "^WARNING" "${ALERT_LOG}" 2>/dev/null || echo 0)

    # Build JSON payload
    local alerts_json="["
    local first=1
    while IFS='|' read -r severity component message recommendation; do
        (( first )) || alerts_json+=","
        first=0
        # Escape quotes in strings
        message=$(echo "$message" | sed 's/"/\\"/g')
        recommendation=$(echo "$recommendation" | sed 's/"/\\"/g')
        alerts_json+="{\"severity\":\"${severity}\",\"component\":\"${component}\",\"message\":\"${message}\",\"recommendation\":\"${recommendation}\"}"
    done < "${ALERT_LOG}"
    alerts_json+="]"

    local payload="{\"hostname\":\"${HOSTNAME_S}\",\"timestamp\":\"${TIME_STAMP}\",\"os\":\"${OS_VERSION}\",\"critical_count\":${critical_count},\"warning_count\":${warning_count},\"alerts\":${alerts_json},\"txt_report\":\"${TXT_FILE}\",\"html_report\":\"${HTML_FILE}\"}"

    # Fire Salt event
    salt-call event.send "${SALT_EVENT_TAG}" "${payload}" --local 2>/dev/null || \
    salt-call event.fire_master "${payload}" "${SALT_EVENT_TAG}" 2>/dev/null || \
    echo "WARNING: Failed to publish Salt event." >&2
}

#=============================================================================
# CLEANUP OLD REPORTS (keep 30 days)
#=============================================================================
cleanup_old_reports() {
    find "${REPORT_DIR}" -name "*_health_*.txt" -mtime +30 -delete 2>/dev/null
    find "${REPORT_DIR}" -name "*_health_*.html" -mtime +30 -delete 2>/dev/null
    find "${REPORT_DIR}" -name ".alert_findings_*.tmp" -mtime +2 -delete 2>/dev/null
}

#=============================================================================
# MAIN EXECUTION
#=============================================================================
main() {
    echo "$(date): Starting Linux Health Check on ${HOSTNAME_S}" >&2

    # Collect all sections into TXT report
    {
        collect_system_info
        collect_cpu_stats
        collect_memory_stats
        collect_swap_stats
        collect_disk_io
        collect_filesystem_stats
        collect_nfs_health
        collect_s3fs_stats
        collect_historical_stats
        generate_recommendations
    } | tee "${TXT_FILE}"

    # Generate HTML from TXT
    generate_html_report "$(cat "${TXT_FILE}")"

    # Alerting
    send_email_alert
    send_salt_event

    # Cleanup
    cleanup_old_reports

    echo "" >&2
    echo "$(date): Health Check Complete" >&2
    echo "  TXT Report : ${TXT_FILE}" >&2
    echo "  HTML Report: ${HTML_FILE}" >&2

    # Return exit code based on findings
    if grep -q "^CRITICAL" "${ALERT_LOG}" 2>/dev/null; then
        exit 2
    elif grep -q "^WARNING" "${ALERT_LOG}" 2>/dev/null; then
        exit 1
    fi
    exit 0
}

main "$@"
